### PR TITLE
Fixes assertion failure in AtomicFreeList used by Job System Allocator

### LINKED ISSUE #524: Crash in Job System Allocator
**Describe the bug**
After a few seconds, filament crashes within the allocator of the job system:
image

**To Reproduce**
1. Create a lot of renderables (100 seem to be enough)
2. Render them continuously

I was able to reproduce this issue with the filament material sandbox sample, by passing monkey.obj a hundred times on the command line. It crashes with the same assert after a few seconds.

**Screenshots**
Crash in material sandbox:
image

My own test scene where this bug occurs:
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA GTX 1080 Ti
 - Backend: OpenGL

**Additional context**
Visual Studio 2017
Clang 7 (same issue occurred on Clang 6)
Compiled in Debug Mode

Stack Trace:
```
engine.dll!utils::AtomicFreeList::pop() Line 236
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\Allocator.h(236)
engine.dll!utils::PoolAllocator<128,64,0,utils::AtomicFreeList>::alloc(unsigned __int64 size, unsigned __int64 alignment, unsigned __int64 offset) Line 317
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\Allocator.h(317)
engine.dll!utils::Arena<utils::PoolAllocator<128,64,0,utils::AtomicFreeList>,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>::alloc(unsigned __int64 size, unsigned __int64 alignment, unsigned __int64 extra) Line 522
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\Allocator.h(522)
engine.dll!utils::Arena<utils::PoolAllocator<128,64,0,utils::AtomicFreeList>,utils::LockingPolicy::NoLock,utils::TrackingPolicy::Untracked>::make<utils::JobSystem::Job,64>() Line 574
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\Allocator.h(574)
engine.dll!utils::JobSystem::allocateJob() Line 227
	at D:\nextgenengine-thirdparty\filament\libs\utils\src\JobSystem.cpp(227)
engine.dll!utils::JobSystem::create(utils::JobSystem::Job * parent, void(*)(void *, utils::JobSystem &, utils::JobSystem::Job *) func) Line 329
	at D:\nextgenengine-thirdparty\filament\libs\utils\src\JobSystem.cpp(329)
engine.dll!utils::JobSystem::createJob<`lambda at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils/JobSystem.h:527:21'>(utils::JobSystem::Job * parent, utils::jobs::details::ParallelForJobData<utils::jobs::CountSplitter<16,8>,std::reference_wrapper<const `lambda at D:\nextgenengine-thirdparty\filament\filament\src\RenderPass.cpp:75:17'> >::parallel::<unnamed-tag> functor) Line 212
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\JobSystem.h(212)
engine.dll!utils::jobs::details::ParallelForJobData<utils::jobs::CountSplitter<16,8>,std::reference_wrapper<const `lambda at D:\nextgenengine-thirdparty\filament\filament\src\RenderPass.cpp:75:17'> >::parallel(utils::JobSystem & js, utils::JobSystem::Job * parent) Line 526
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\JobSystem.h(526)
engine.dll!utils::jobs::details::ParallelForJobData<utils::jobs::CountSplitter<16,8>,std::reference_wrapper<const `lambda at D:\nextgenengine-thirdparty\filament\filament\src\RenderPass.cpp:75:17'> >::parallelWithJobs(utils::JobSystem & js, utils::JobSystem::Job * parent) Line 468
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\JobSystem.h(468)
engine.dll!utils::JobSystem::createJob<utils::jobs::details::ParallelForJobData<utils::jobs::CountSplitter<16,8>,std::reference_wrapper<const `lambda at D:\nextgenengine-thirdparty\filament\filament\src\RenderPass.cpp:75:17'> >,&utils::jobs::details::ParallelForJobData<utils::jobs::CountSplitter<16, 8>, std::reference_wrapper<const (lambda at D:\nextgenengine-thirdparty\filament\filament\src\RenderPass.cpp:75:17)> >::parallelWithJobs>::stub::call(void * user, utils::JobSystem & js, utils::JobSystem::Job * job) Line 192
	at D:\nextgenengine-thirdparty\filament\libs\utils\include\utils\JobSystem.h(192)
engine.dll!utils::JobSystem::execute(utils::JobSystem::ThreadState & state) Line 262
	at D:\nextgenengine-thirdparty\filament\libs\utils\src\JobSystem.cpp(262)
```

Sadly I got no clue about the allocators being used here, so maybe the following screenshots of the local variables might help diagnosing this issue:

image

image

### PR DESCRIPTION
**Pull request by shartte**
I believe this fixes #524, given the following rationale:

The assert on `next` should not occur before `compare_exchange_weak` succeeds, because only that indicates the absence of a race condition.

Between the atomic load of `mHead` and `storage[currentHead.offset].next`, another thread might have already returned the storage pointed at by mHead to a caller, which could have overwritten the memory with it's own data (hence making it moot to assert anything about the value of `next`).

It would also be nice if someone could check if the comments I added are actually correct.

After making this change, I tested both my app and the material_sandbox with 100 monkeys, and both didn't crash anymore.

### CODE REVIEW

File: libs/utils/include/utils/Allocator.h [hunk 1]
```diff
@@ -232,9 +232,12 @@ class AtomicFreeList {
         HeadPtr currentHead = mHead.load();
         while (currentHead.offset >= 0) {
             Node* const next = storage[currentHead.offset].next.load(std::memory_order_relaxed);
-            assert(!next || next >= storage);
             newHead = { next ? int32_t(next - storage) : -1, currentHead.tag + 1 };
             if (mHead.compare_exchange_weak(currentHead, newHead)) {
+                // This assert needs to occur after we have validated that there was no race condition
```
Comment (pixelflinger) [inline libs/utils/include/utils/Allocator.h]: Very good catch. Thanks! 

I think this deserves even more commenting :-)

On line 235 we do use `next` to populate `newHead`, and now we're saying that we can't rely on the value of `next` at that point. In particular we're doing `next - storage`, what if `next` already contains user data?
This works because in that case we will loop because of the changing `tag`, and no harm is done.

Maybe just add a comment explaining that too?
