### PR TITLE
Fix Metal sampler binding and memory leak

### LINKED ISSUE #1008: iOS hello-pbr example is crashing in MetalDriver::draw
**Describe the bug**
The iOS sample hello-pbr-Metal target is crashing after creating the first frame, while the hello-pbr-OpenGL target is working fine.

**To Reproduce**
1. Build hello-pbr with the Metal target.
2. Run on device.

**Expected behavior**
The Metal target should work the same as the OpenGL target.

**Screenshots**

image

**Smartphone (please complete the following information):**
 - Device: iPad Pro 10.5
 - OS: iOS 12.1.4

**Additional context**

Locals
```
this	filament::driver::metal::MetalDriver *	0x283897800	0x0000000283897800
ps	filament::Driver::PipelineState	
rph	filament::Driver::RenderPrimitiveHandle	
primitive	filament::driver::metal::MetalRenderPrimitive *	0x283bb4a50	0x0000000283bb4a50
program	filament::driver::metal::MetalProgram *	0x2833b46e0	0x00000002833b46e0
rs	const filament::Driver::RasterState &	0x000000016b9d6794
pipelineState	filament::driver::metal::PipelineState	
cullMode	MTLCullMode	MTLCullModeBack
depthState	filament::driver::metal::DepthStencilState	
clearFlags	filament::Driver::TargetBufferFlags	DEPTH_AND_STENCIL
range	NSRange	location=0, length=16	
bufferRange	NSRange	location=4504147536, length=6100444864	
indexBuffer	filament::driver::metal::MetalIndexBuffer *	0x32350105e5b5a0	0x0032350105e5b5a0

```

### PR DESCRIPTION
**Pull request by bejado**
Update Metal driver to use new `SamplerGroupInfo`. We're no longer keeping track of which textures / samplers are already bound to the command encoder as the process was error-prone and isn't worth the effort for now.

Also fixed a memory leak when creating a new depth texture inside of `createRenderTargetR`.

Fixes #1008

### CODE REVIEW

File: filament/src/driver/metal/MetalDriver.mm [hunk 1]
```diff
@@ -54,8 +54,8 @@
 }
 
 MetalDriver::~MetalDriver() noexcept {
-    delete mContext;
     [mContext->device release];
+    delete mContext;
```
Comment (pixelflinger) [inline filament/src/driver/metal/MetalDriver.mm]: Good one!
