### PR TITLE
Fix pathing issues on Windows

### LINKED ISSUE #13: The win32 implementation of getCanonicalPath doesn't work the same as the base implementation
Win32 implementation calls the Windows SDK function PathCanonicalize but it only works correctly when called with a fully qualified path it seems.

Example : the README for Windows says to test the compiled code with
`./samples/material_sandbox --ibl=../samples/envs/office ../assets/models/sphere/sphere.obj`

This results directly in calling getCanonicalPath with `../samples/envs/office` which then returns `samples/envs/office` and then the IBL isn't found.

The same issue applies directly to the path for the obj file to open.

Workaround : pass absolute paths. This doesn't work for the IBL though because of another issue later on with path concatenation.

### LINKED ISSUE #14: Path::isAbsolute() doesn't work for Win32 paths
It checks if the path starts with / even for Win32 paths. As a result, getAbsolutePath doesn't work either.

### PR DESCRIPTION
**Pull request by bejado**
Fix `Path::split`, `Path::isAbsolute`, `Path::getParent`, and `getCanonicalPath` on Windows.

Fixes #13 
Fixes #14

Some edge-case windows pathing may still not work:
- "drive relative" paths: "C:tmp.txt"
- UNC paths (network paths): "\\foo\\bar" (will be collapsed to \foo\bar, which may resolve to a different location than expected)
- "absolute paths": "\foo\bar" (may or may not resolve to drive root)

### CODE REVIEW

File: libs/utils/src/win32/Path.cpp [hunk 1]
```diff
@@ -1,74 +1,70 @@
-/*
```
Comment (bejado) [inline libs/utils/src/win32/Path.cpp]: Changed line endings to UNIX style, hence the massive diff
