### PR TITLE
Fix Catalina by moving some calls to the UI thread.

### LINKED ISSUE #1839: EXC_BAD_INSTRUCTION with 2016 MacBook
clang 11 + catalina is somehow emitting instructions that my CPU doesn't recognize.  I am using a Skylake processor (M3-6Y30).

Maybe they are AVX-512 instructions but I'm not sure yet.

Easy to repro, just run any of our samples, e.g. `gltf_viewer`

### PR DESCRIPTION
**Pull request by prideout**
Fixes #1839.

### CODE REVIEW

File: filament/backend/src/opengl/PlatformCocoaGL.mm [hunk 1]
```diff
@@ -115,14 +115,20 @@
         glGetIntegerv(GL_VIEWPORT, viewport);
         glGetIntegerv(GL_SCISSOR_BOX, scissor);
```
Comment (bejado) [inline filament/backend/src/opengl/PlatformCocoaGL.mm]: Saving and recalling the viewport / scissor state here shouldn't be needed anymore.

Comment (prideout) [reply filament/backend/src/opengl/PlatformCocoaGL.mm]: Okay, added a commit for this.
