### PR TITLE
gltfio: enable extended implementation

### LINKED ISSUE #6358: SurfaceOrientation doesn't duplicate vertices when generating flat normals
**Describe the bug**
I am having two (separate I believe) issues rendering some meshes in Filament. I'm only opening one issue because they are both related to the same mesh type. We generate many meshes of this type, and the issue is not confined to this specific mesh, but all meshes of this type. First, this is what the mesh looks like in scenekit:

scenekit

***Issue 1***

The Filament directional lights only illuminate parts of the scene. This is clear if I light the scene with only a directional light. This issue appears in our viewer as well as the sample-gltf iOS viewer. As you can see a large chunk of the ground plane is not illuminated by the light (maybe there is a setting to fix this, but I played with all that seemed relevant)

filament_directional_only

At first I thought it was maybe an issue on our side with the triangulation, but as you can see in meshlab the ground plane only has two triangles and appear to be unrelated to the illumination boundaries

meshlab

*** Issue 2 ***

The colors for the mesh are pretty far off from what they are in all other viewers (SceneKit, MeshLab, ThreeJS). In particular they appear to be much less saturated. I have tried adjusting the colors and intensity of the lights but this did not fix it. Here is what it looks like in Filament when I adjusted the directional and indirect lights to be as good as I could make them

filament_directional_plus_indirect

**To Reproduce**

Load this .glb in filament and observe the issues:

[house.glb.zip](https://github.com/google/filament/files/10178644/house.glb.zip)

These were my exact lighting settings:

```
    math::float3 harmonics[1];
    harmonics[0] = math::float3(1.0f, 1.0f, 1.0f);
    indirect_light_ = IndirectLight::Builder().irradiance(1, harmonics).intensity(24000).build(*engine_);
    if (indirect_light_ == nullptr) {
      throw std::runtime_error("Creating a filament indirect light failed!");
    }
    scene_->setIndirectLight(indirect_light_);

    // Lights and shadows for room mode captures
    utils::Entity light = utils::EntityManager::get().create();
    LightManager::ShadowOptions shadowOptions;
    shadowOptions.shadowCascades = 3;
    shadowOptions.mapSize = 4096;
    shadowOptions.vsm.blurWidth = 120;
    shadowOptions.vsm.msaaSamples = 16;

    LightManager::Builder(LightManager::Type::DIRECTIONAL)
        .color(Color::toLinear<ACCURATE>({0.98f, 0.9f, 0.86f}))
        .intensity(38000)
        .direction({0.2, -1, -0.3})
        .castShadows(true)
        .shadowOptions(shadowOptions)
        .build(*engine_, light);
    scene_->addEntity(light);
```

**Expected behavior**

**Screenshots**

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: tested on iOS, Mac, Android and WebGL
 - GPU: All tested
 - Backend: Tested on OpenGL, Metal and WebGL

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2]
 - OS: [e.g. Android Pie 9.0]

**Additional context**

### PR DESCRIPTION
**Pull request by poweifeng**
This change will enable proper flat-shading and MikkTSpace.

Fixes #6358, #7444

## Flat Shading comparison (model from #6358)

Before:
image

After: 
image

## Tangent space comparison (model from #7444)

Before:
image

After: 
image

### CODE REVIEW

File: samples/gltf_viewer.cpp [hunk 1]
```diff
@@ -747,14 +747,25 @@ int main(int argc, char** argv) {
                 createJitShaderProvider(engine, OPTIMIZE_MATERIALS) :
                 createUbershaderProvider(engine, UBERARCHIVE_DEFAULT_DATA, UBERARCHIVE_DEFAULT_SIZE);
 
-        app.assetLoader = AssetLoader::create({engine, app.materials, app.names });
+        AssetConfigurationExtended extConfig = {};
```
Comment (romainguy) [inline samples/gltf_viewer.cpp:750]: You're not doing anything with `extConfig`. You only set its gltfPath but you don't pass the config to anything.

File: libs/gltfio/include/gltfio/AssetLoader.h [hunk 2]
```diff
@@ -38,6 +38,18 @@ namespace filament::gltfio {
...
+// Use this struct to enable mikktspace-based tangent-space computation.
+/**
+ * \struct AssetConfigurationExtended AssetLoader.h gltfio/AssetLoader.h
+ * \brief extends struct AssetConfiguration
+ * Useful if client needs mikktspace tangents.
+ */
+struct AssetConfigurationExtended {
+    //! Optional The same parameter as provided to \struct ResourceConfiguration ResourceLoader.h
+    //! gltfio/ResourceLoader.h
+    char const* gltfPath;
```
Comment (romainguy) [inline libs/gltfio/include/gltfio/AssetLoader.h:50]: I don't understand why this is realted to mikkt space? Why would setting a glTF path in a separate struct change the tangent space computations? This doesn't seem like a user-friendly API (and does it mean it only works with local files?)

File: libs/gltfio/include/gltfio/AssetLoader.h [hunk 3]
```diff
@@ -62,6 +74,9 @@ struct AssetConfiguration {
 
     //! Optional default node name for anonymous nodes
     char* defaultNodeName = nullptr;
+
+    //! Optional to enable mikktspace tangents.
+    AssetConfigurationExtended* ext = nullptr;
```
Comment (bejado) [inline libs/gltfio/include/gltfio/AssetLoader.h:79]: Maybe comment on the required lifetime for this pointer? Based on the code it seems like it only needs to exist during `AssetLoader::create`

File: samples/gltf_viewer.cpp (hunk 1 above)
Comment (poweifeng) [reply samples/gltf_viewer.cpp:750]: sorry, I did not mean to commit gltf_viewer changes.  That was just for testing.  I undid the changes

File: libs/gltfio/include/gltfio/AssetLoader.h (hunk 2 above)
Comment (poweifeng) [reply libs/gltfio/include/gltfio/AssetLoader.h:50]: Yes, deally, we'd just add support for mikktspace without changing the existing API, but that's not possible with how AssetLoader/ResourceLoader is structured.  I opted to introduce minimal changes to existing API to address the opened bugs.  So that any use case with the right criteria (desktop and only disk resources) can make use of it. But, the real, long-term solution should be a new loader API (separate from AssetLoader/ResourceLoader) that would better fit the assumption of running a remeshing algo like mikktspace.

File: libs/gltfio/include/gltfio/AssetLoader.h (hunk 3 above)
Comment (poweifeng) [reply libs/gltfio/include/gltfio/AssetLoader.h:81]: Good point.  Comment added.

File: libs/gltfio/include/gltfio/AssetLoader.h (hunk 2 above)
Comment (poweifeng) [reply libs/gltfio/include/gltfio/AssetLoader.h:51]: I added some comments in the header and in the commit to be more explicit about this approach's limitation.

Comment (pixelflinger) [reply libs/gltfio/include/gltfio/AssetLoader.h:51]: ah.. we should probably have a bug open then.

Comment (poweifeng) [reply libs/gltfio/include/gltfio/AssetLoader.h:51]: good point, I filed #7782 for tracking.

File: libs/gltfio/src/AssetLoader.cpp [hunk 4]
```diff
@@ -202,14 +205,22 @@ class MaterialInstanceCache {
...
             mNameManager(config.names),
             mTransformManager(config.engine->getTransformManager()),
             mMaterials(*config.materials),
             mEngine(*config.engine),
-            mDefaultNodeName(config.defaultNodeName) {}
+            mDefaultNodeName(config.defaultNodeName) {
+        if (config.ext) {
+#if defined(__ANDROID__) || defined(IOS) || defined(__EMSCRIPTEN__)
+            PANIC_PRECONDITION("Extend asset loading is not supported on this platform");
+#endif
```
Comment (pixelflinger) [inline libs/gltfio/src/AssetLoader.cpp:219]: Is there a way to query if it's supported?

**Review by pixelflinger — APPROVED** [review]

File: libs/gltfio/src/AssetLoader.cpp (hunk 4 above)
Comment (poweifeng) [reply libs/gltfio/src/AssetLoader.cpp]: moved this to a static method so that client can use the method to check for support.
