### PR TITLE
OpenGL driver: fix error with uvec4 attribs, clean up Vulkan/Metal.

### LINKED ISSUE #1726: Morph shapes not rendering
**Describe the bug**
I'm not getting a render in filament.js for any of the glTF sample models that include morphing. The console (on Chrome) is giving a lot of these: `GL ERROR :GL_INVALID_OPERATION : glDrawElements: vertexAttrib function must match shader attrib type`

**To Reproduce**
You can see our results here: https://googlewebcomponents.github.io/model-viewer/test/fidelity/results-viewer.html and if you serve model-viewer locally you can also see them live here: http://localhost:8000/test/fidelity/renderers/filament/

The problem models are khronos-AnimatedMorphCube, khronos-AnimatedMorphSphere, and khronos-MorphPrimitivesTest

### PR DESCRIPTION
**Pull request by prideout**
The vertex shader in the material variant for skinning-and-morphing
declares a `uvec4` attribute that can be unused and disabled, but still
needs to be typed correctly.

The fix is motivated by WebGL, but the issue might occur with other
OpenGL implementations that have strict drivers.

Fixes #1726

### CODE REVIEW

File: filament/backend/src/opengl/OpenGLDriver.cpp [hunk 1]
```diff
@@ -2032,6 +2032,13 @@ void OpenGLDriver::setRenderPrimitiveBuffer(Handle<HwRenderPrimitive> rph,
 
                 gl.enableVertexAttribArray(GLuint(i));
             } else {
+
+                // In some OpenGL implementations, we must supply a properly-typed placeholder for
+                // every integer input that is declared in the vertex shader.
+                if (UTILS_UNLIKELY(eb->attributes[i].flags & Attribute::FLAG_INTEGER_TARGET)) {
+                    glVertexAttribI4ui(GLuint(i), 0, 0, 0, 0);
+                }
```
Comment (pixelflinger) [inline filament/backend/src/opengl/OpenGLDriver.cpp]: I think we should also have the `else` case here
