### PR TITLE
Fix support for 565 textures

### LINKED ISSUE #2336: Support for Android RGB565 bitmaps
Is it possible to load a Bitmap as RGB565 and send it through to Filament using _TextureHelper.setBitmap_ so that it ends up as GL_RGB565 texture type?

I'm trying to find a more memory efficient way to store uncompressed opaque textures than RGBA8.

### PR DESCRIPTION
**Pull request by romainguy**
This requires exposing a new `USHORT_565` pixel data type. Fixes #2336.

### CODE REVIEW

File: filament/backend/include/backend/DriverEnums.h [hunk 1]
```diff
@@ -248,16 +248,17 @@ enum class PixelDataFormat : uint8_t {
...
+    BYTE,                 //!< signed byte
+    USHORT,               //!< unsigned short (16-bit)
+    SHORT,                //!< signed short (16-bit)
+    UINT,                 //!< unsigned int (16-bit)
+    INT,                  //!< signed int (32-bit)
+    HALF,                 //!< half-float (16-bit float)
+    FLOAT,                //!< float (32-bits float)
+    COMPRESSED,           //!< compressed pixels, @see CompressedPixelDataType
+    UINT_10F_11F_11F_REV, //!< three low precision floating-point numbers
+    USHORT_565            //!< unsigned int (16-bit), encodes 3 RGB channels
```
Comment (prideout) [inline filament/backend/include/backend/DriverEnums.h:261]: We should probably go ahead and add to `jsenums.cpp` and `filament.d.ts` and `Texture.java`

Comment (romainguy) [reply filament/backend/include/backend/DriverEnums.h:261]: It is in Texture.java already. I'll update the js bindings.

Comment (romainguy) [reply filament/backend/include/backend/DriverEnums.h:261]: Done. ptal.
