### PR TITLE
Initialize object_uniforms in depth shader

### LINKED ISSUE #6487: Picking broken in 1.30.0
**Describe the bug**
asset->getName always returns null in 1.30.0

**To Reproduce**
1. Build 1.30.0
2. Run gltf_viewer 
  **Expected behavior** **Expected behavior**
asset->getName should return the name of the node 
**Screenshots**
image
Screen Shot 2023-01-24 at 12 51 13 PM
Screen Shot 2023-01-24 at 12 50 15 PM

**Logs**
If applicable, copy logs from your console here. Please *do not*
use screenshots of logs, copy them as text.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - GPU: [e.g. NVIDIA GTX 1080] 
 - Backend: [OpenGL/Vulkan] Metal 

**Additional context**
You can see in the images that the gltf_viewer correctly displayed the name of the asset entity in the UI before 1.30.0 and no longer does in 1.30.0.  The listed commit is the one where we can verify it stopped working.

### PR DESCRIPTION
**Pull request by bejado**
Fixes #6487

### CODE REVIEW

**Review by poweifeng — APPROVED** [review]

File: shaders/src/depth_main.fs [hunk 1]
```diff
@@ -47,6 +47,7 @@ void main() {
     fragColor.xy = computeDepthMomentsVSM(depth);
     fragColor.zw = computeDepthMomentsVSM(-1.0 / depth); // requires at least RGBA16F
 #elif defined(VARIANT_HAS_PICKING)
+    initObjectUniforms(object_uniforms); // only needed for picking
```
Comment (pixelflinger) [inline shaders/src/depth_main.fs:50]: I would be more confortable moving this just under the `filament_lodBias - ` line.

I think it's okay to protect it with `#ifdef VARIANT_HAS_PICKING` but with a comment stating that currently it's only used in that case. But I think it'll be safer to not even do that and let the compiler eliminate the unneeded code.

**Review by pixelflinger — CHANGES_REQUESTED** [review]
