### PR TITLE
vulkan: Add fallback extent for swap chain sizing

### LINKED ISSUE #6094: VulkanSwapChain::create sizing
**Describe the bug**

Running on Linux Wayland with two different Vulkan drivers I am seeing VulkanSwapChain::create fail.

**NVIDIA RTX A2000 Laptop GPU**

Error
```
VULKAN ERROR: (VUID-VkSwapchainCreateInfoKHR-imageExtent-01274) Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x7fa4b499bcc0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (4294967295,4294967295), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (4294967295,4294967295), minImageExtent = (1,1), maxImageExtent = (16384,16384). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
```

**Intel(R) UHD Graphics (TGL GT1)**

Error
```
VULKAN ERROR: (VUID-VkSwapchainCreateInfoKHR-imageExtent-01274) Validation Error: [ VUID-VkSwapchainCreateInfoKHR-imageExtent-01274 ] Object 0: handle = 0x7fd39c99bcc0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0x7cd0911d | vkCreateSwapchainKHR() called with imageExtent = (4294967295,4294967295), which is outside the bounds returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR(): currentExtent = (4294967295,4294967295), minImageExtent = (1,1), maxImageExtent = (16384,16384). The Vulkan spec states: imageExtent must be between minImageExtent and maxImageExtent, inclusive, where minImageExtent and maxImageExtent are members of the VkSurfaceCapabilitiesKHR structure returned by vkGetPhysicalDeviceSurfaceCapabilitiesKHR for the surface (https://vulkan.lunarg.com/doc/view/1.3.216.0/linux/1.3-extensions/vkspec.html#VUID-VkSwapchainCreateInfoKHR-imageExtent-01274)
```

**Expected behavior**
Swap Chain is created

**Desktop (please complete the following information):**
 - OS: Linux
 - GPU: NVIDIA RTX A2000 Laptop GPU/PCIe/SSE2, Mesa Intel® UHD Graphic, AMD® Radeon rx 6800
 - Backend: Vulkan

**Notes**

If I implement this code in place of `clientSize = caps.currentExtent;`:
```
    if (caps.currentExtent.width != UINT32_MAX) {
        // If the surface reports a specific extent, we must use it.
        clientSize = caps.currentExtent;
    } else {
        VkExtent2D actual_extent = {
                .width = 1920, // Wayland surface size in pixels
                .height = 720,  // Wayland surface size in pixels
        };
        clientSize.width =
                std::max(caps.minImageExtent.width,
                         std::min(caps.maxImageExtent.width,
                                  actual_extent.width));
        clientSize.height =
                std::max(caps.minImageExtent.height,
                         std::min(caps.maxImageExtent.height,
                                  actual_extent.height));
    }
```
It will always succeed and ends up with the Wayland surface size:
```
vkCreateSwapchain: 1920x720, VK_FORMAT_B8G8R8A8_SRGB, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 5, 1
```

test_bluevk runs on the same setup without issue.

This would require querying the native window for it's target size.

### PR DESCRIPTION
**Pull request by poweifeng**
Fixes #6094

### CODE REVIEW

File: filament/backend/include/backend/platforms/VulkanPlatform.h [hunk 1]
```diff
@@ -30,6 +30,13 @@ class VulkanPlatform : public Platform {
     // Given a Vulkan instance and native window handle, creates the platform-specific surface.
     virtual void* createVkSurfaceKHR(void* nativeWindow, void* instance, uint64_t flags) noexcept = 0;
 
+    // We use the extent of the surface to determine the size of the swap chain. For platforms
+    // where vkGetPhysicalDeviceSurfaceCapabilitiesKHR returns undefined surface extent, we use
+    // this fallback as the request size for the swap chain.
+    // This can be a no-op for most platforms.
+    virtual void getSwapChainFallbackExtent(void* nativeWindow, uint32_t* width, uint32_t* height)
+            noexcept {}
```
Comment (pixelflinger) [inline filament/backend/include/backend/platforms/VulkanPlatform.h:38]: Implement the virtual in a cpp. This is because it is a public API, so the implementation should be "on our side".

File: filament/backend/src/vulkan/PlatformVkLinuxWayland.cpp [hunk 2]
```diff
@@ -63,4 +67,11 @@ void* PlatformVkLinuxWayland::createVkSurfaceKHR(void* nativeWindow, void* insta
     return surface;
 }
 
+void PlatformVkLinuxWayland::getSwapChainFallbackExtent(void* nativeWindow, uint32_t* width,
+        uint32_t* height) noexcept {
+    wl* ptrval = reinterpret_cast<wl*>(nativeWindow);
+    *width = ptrval->width;
+    *height = ptrval->height;
```
Comment (pixelflinger) [inline filament/backend/src/vulkan/PlatformVkLinuxWayland.cpp:74]: why do we need a new virtual and not do this during create swapchain?

**Review by pixelflinger — CHANGES_REQUESTED** [review]

File: filament/backend/src/vulkan/PlatformVkLinuxWayland.cpp (hunk 2 above)
Comment (pixelflinger) [reply filament/backend/src/vulkan/PlatformVkLinuxWayland.cpp:74]: I think the issue is that `createVkSurfaceKHR` should return a type that we define (that can contain the width/height etc) + a pointer to the native surface -- instead of returning a pointer to the native surface directly as a void*.

Comment (poweifeng) [reply filament/backend/src/vulkan/PlatformVkLinuxWayland.cpp]: done.  

I think my initial thoughts are not to make `createVkSurfaceKHR` do more things than necessary.  But I guess I'm passing the extent in `nativeWindow` anyways.

File: filament/backend/include/backend/platforms/VulkanPlatform.h [hunk 3]
```diff
@@ -27,8 +27,18 @@ namespace filament::backend {
 
 class VulkanPlatform : public Platform {
 public:
+    struct SurfaceBundle {
+        void* surface;
+        // On certain platforms, the extent of the surface cannot be queried from Vulkan. In those
+        // situations, we allow the frontend to pass in the extent to use in creating the swap
+        // chains.
```
Comment (bejado) [inline filament/backend/include/backend/platforms/VulkanPlatform.h:34]: Maybe add a note that `width` and `height` can be set to zero for the default behavior.

**Review by bejado — APPROVED** [review]

File: filament/backend/src/vulkan/PlatformVkCocoa.mm [hunk 4]
```diff
@@ -53,10 +56,17 @@
...
     createInfo.sType = VK_STRUCTURE_TYPE_MACOS_SURFACE_CREATE_INFO_MVK;
     createInfo.pView = (__bridge void*) nsview;
-    VkResult result = vkCreateMacOSSurfaceMVK((VkInstance) instance, &createInfo, VKALLOC, &surface);
+
+    SurfaceBundle bundle {
+        .surface = nullptr,
+        .width = 0,
+        .height = 0
+    };
+    VkResult result = vkCreateMacOSSurfaceMVK((VkInstance) instance, &createInfo, VKALLOC,
```
Comment (bejado) [inline filament/backend/src/vulkan/PlatformVkCocoa.mm:65]: You can get rid of the `VKSurfaceKHR surface` declaration above

File: filament/backend/src/vulkan/PlatformVkCocoaTouch.mm [hunk 5]
```diff
@@ -57,13 +65,12 @@
     createInfo.pNext = NULL;
     createInfo.flags = 0;
     createInfo.pView = metalLayer;
-    VkResult result = vkCreateIOSSurfaceMVK((VkInstance) instance, &createInfo, VKALLOC, &surface);
```
Comment (bejado) [inline filament/backend/src/vulkan/PlatformVkCocoaTouch.mm:60]: You can get rid of the `VKSurfaceKHR surface` declaration above

File: filament/backend/src/vulkan/PlatformVkLinuxGGP.cpp [hunk 6]
```diff
@@ -62,13 +69,12 @@ void* PlatformVkLinuxGGP::createVkSurfaceKHR(void* nativeWindow, void* instance,
   VkSurfaceKHR surface = nullptr;
```
Comment (bejado) [inline filament/backend/src/vulkan/PlatformVkLinuxGGP.cpp:69]:
```suggestion
```

Comment (poweifeng) [reply filament/backend/src/vulkan/PlatformVkLinuxGGP.cpp]: done

File: filament/backend/src/vulkan/PlatformVkCocoaTouch.mm (hunk 5 above)
Comment (poweifeng) [reply filament/backend/src/vulkan/PlatformVkCocoaTouch.mm:60]: done

File: filament/backend/src/vulkan/PlatformVkCocoa.mm (hunk 4 above)
Comment (poweifeng) [reply filament/backend/src/vulkan/PlatformVkCocoa.mm:64]: done

File: filament/backend/include/backend/platforms/VulkanPlatform.h (hunk 3 above)
Comment (poweifeng) [reply filament/backend/include/backend/platforms/VulkanPlatform.h]: done

File: filament/backend/src/vulkan/VulkanSwapChain.cpp [hunk 7]
```diff
@@ -23,6 +23,10 @@
 using namespace bluevk;
 using namespace utils;
 
+namespace {
+constexpr uint32_t VULKAN_UNDEFINED_EXTENT = 0xFFFFFFFF;
```
[the remark this answers is not in the document]
Comment (poweifeng) [reply filament/backend/src/vulkan/VulkanSwapChain.cpp:27]: Yeah: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkSurfaceCapabilitiesKHR.html#_description

**Review by pixelflinger — APPROVED** [review]
