### PR TITLE
Try to clean up asset folders for sample apps.

### LINKED ISSUE #11: (Some) examples don't work
`./hellotriangle`

```
FEngine (64 bits) created at 0x10a798000
FEngine resolved backend: Vulkan
[mvk-info] MoltenVK version 1.0.8. Vulkan version 1.0.73.
[mvk-info] GPU device:
		model: AMD Radeon Pro 450
		type: Discrete
		vendorID: 0x1002
		deviceID: 0x67ef
		pipelineCacheUUID: 00000000-0000-0000-0000-271300002718
	supports the following Metal Feature Sets:
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
[mvk-info] GPU device:
		model: Intel(R) HD Graphics 530
		type: Integrated
		vendorID: 0x8086
		deviceID: 0x191b
		pipelineCacheUUID: 00000000-0000-0000-0000-271300002718
	supports the following Metal Feature Sets:
		macOS GPU Family 1 v3
		macOS GPU Family 1 v2
		macOS GPU Family 1 v1
Selected physical device: AMD Radeon Pro 450
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 450
[mvk-info] Created 2 swapchain images with initial size (2048, 1280).
vkCreateSwapchain: 2048x1280, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 2
[***MoltenVK ERROR***] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (error code 1):
Timeout after 125.000 milliseconds. Likely internal Metal compiler error.
froxel arena: High watermark 0 KiB (0%)
froxel arena: High watermark 0 KiB (0%)
Renderer: Commands High watermark 0 KiB (0%), 3 commands, 40 bytes/command
CircularBuffer: High watermark 5 KiB (0%)
cleaning up 1 leaked filament::details::FMaterial
Destroying 0 descriptor sets.
per-renderpass allocator arena: High watermark 1023 KiB (16%)
```

---

`./hellopbr`

```
[...]
Selected physical device: AMD Radeon Pro 450
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 450
The specified IBL path does not exist: ../samples/envs/office
[1]    88881 segmentation fault  ./hellopbr
```

---

`./shadowtest`

```
[...]
Selected physical device: AMD Radeon Pro 450
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 450
The specified IBL path does not exist: ../samples/envs/office
[1]    89676 segmentation fault  ./shadowtest
```

---

`./texturedquad`

```
[...]
Selected physical device: AMD Radeon Pro 450
[mvk-info] Created VkDevice to run on GPU AMD Radeon Pro 450
Loaded texture: 2048x2048
[mvk-info] Created 2 swapchain images with initial size (2048, 1280).
vkCreateSwapchain: 2048x1280, VK_FORMAT_B8G8R8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, 2
[1]    89815 segmentation fault  ./texturedquad
```

---

image

### PR DESCRIPTION
**Pull request by prideout**
This removes the build step where we copy a subset of assets, and makes
it so that FilamentApp hands out a "root path" for assets. For now this
is determined based on the location of the executable. This allows
developers to launch samples from any CWD.

Closes #11

### CODE REVIEW

File: samples/app/FilamentApp.h [hunk 1]
```diff
@@ -77,6 +79,13 @@ class FilamentApp {
     FilamentApp& operator=(const FilamentApp& rhs) = delete;
     FilamentApp& operator=(FilamentApp&& rhs) = delete;
 
+    // Returns the path to the Filament root for loading assets. For now this is determined by
+    // looking up from the executable folder, which allows users to launch samples from any folder.
+    static const utils::Path& getRootPath() {
+        static const utils::Path root = utils::Path::getCurrentExecutable().getAncestor(3);
```
Comment (romainguy) [inline samples/app/FilamentApp.h]: This assumes we always run samples from out/xxx/samples. This will break if someone builds manually with cmake or if we distribute the samples in a zip file.

Comment (prideout) [reply samples/app/FilamentApp.h]: Yup, and we were already making this assumption in some places, this merely consolidates the badness.

Maybe I should add back the asset-copying stuff to CMake, which would allow me to replace getAncestor with getParent...

Comment (romainguy) [reply samples/app/FilamentApp.h]: I think that's the best solution.

Comment (prideout) [reply samples/app/FilamentApp.h]: Done.
