### PR TITLE
Fix regression with getDefaultInstance().

### LINKED ISSUE #2164: getDefaultInstance() has regressed (desktop + web)
- `triangle.html` and `skinning.html` are invisible.
- `vk_hellotriangle` is invisible, even when using GL backend.

### PR DESCRIPTION
**Pull request by prideout**
This caused color writes to be disabled in our "hello triangle" samples.

Fixes #2164.

### CODE REVIEW

File: filament/src/MaterialInstance.cpp [hunk 1]
```diff
@@ -76,9 +76,15 @@ FMaterialInstance::FMaterialInstance(FEngine& engine, FMaterial const* material)
 void FMaterialInstance::initDefaultInstance(FEngine& engine, FMaterial const* material) {
     mMaterial = material;
 
+    const RasterState& rasterState = mMaterial->getRasterState();
```
Comment (bejado) [inline filament/src/MaterialInstance.cpp]: If I remember correctly, I think we've had issues here before changing this logic in the constructor but not here or vice versa. I wonder if we could refactor this function and the `FMaterialInstance` constructor to call a helper function instead to avoid duplicating this logic.

Comment (prideout) [reply filament/src/MaterialInstance.cpp]: Good idea, I added a commit that renames and repurposes `initParameters()` for this.
