### PR TITLE
gltfio: Fix tangents when morphing is enabled.

### LINKED ISSUE #1609: GLTFIO morph target tangents
I'm not sure that morph target tangents are being processed properly when importing GLTF models into Filament. Consider [AnimatedMorphCube](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube), which has a sloping animated face. With a single directional light source we would expect to see some variation on the sloping face as seen in [this PR](https://github.com/KhronosGroup/glTF-Sample-Models/pull/171). Instead we see something like this:

Screenshot 2019-09-09 at 14 56 31
Screenshot 2019-09-09 at 14 56 19

I'm trying to do the same import in my own engine and I was hoping to copy from GLTFIO. Looking at the code I can't quite work out how it can use the same function to combine GLTF normals and tangents in the morph targets that is uses for the base primitive normals and tangents. The morph targets are deltas, but the base attributes are absolute values. I may of course be missing something subtle that is happening prior to getting to that point in the code.

### PR DESCRIPTION
**Pull request by prideout**
The vertex data for glTF morph targets are deltas rather than final
values, so we were passing incorrect data into the SurfaceOrientation
helper.

This has been a long-standing bug that affected models with morphing,
including Buster Drone. However in practice we have observed visual
issues only with AnimatedMorphCube.

Tested against AnimatedMorphCube, Buster Drone, Cesium Man, Fox, and
Littlest Tokyo.

Fixes #1609

### CODE REVIEW

File: libs/gltfio/src/ResourceLoader.cpp [hunk 1]
```diff
@@ -784,114 +784,130 @@ void ResourceLoader::Impl::computeTangents(FFilamentAsset* asset) {
...
+        }
+        if (isMorphTarget) {
             const cgltf_morph_target& morphTarget = prim.targets[morphTargetIndex];
             for (cgltf_size aindex = 0; aindex < morphTarget.attributes_count; aindex++) {
                 const cgltf_attribute& attr = morphTarget.attributes[aindex];
                 if (attr.index == 0) {
-                    accessors[attr.type] = attr.data;
-                    vertexCount = attr.data->count;
+                    assert(baseAccessors[attr.type] &&
+                            "Morph target data has no corresponding base vertex data.");
```
Comment (romainguy) [inline libs/gltfio/src/ResourceLoader.cpp:818]: I never thought of doing that to add a message to an assert!

**Review by romainguy — APPROVED** [review]
🥳

**Review by pixelflinger — APPROVED** [review]
