### PR TITLE
Fix MSVC 2019 16.4 build

### LINKED ISSUE #1939: Build FAILED on Win10 by msvc 2019 16.4.0
Build FAILED on Win 10 by msvc 2019 16.4.0, the error message follow:

6>Done building project "textures.vcxproj".
5>SurfaceOrientation.cpp
5>.\filament-1.4.3\libs\math\include\math/TVecHelpers.h(54,24): error C2938: 'std::enable_if_t<false,void>' : Failed to specialize alias template
5>.\filament-1.4.3\libs\math\include\math/TVecHelpers.h(54): message : see reference to alias template instantiation 'std::enable_if_t<false,void>' being compiled
5>.\filament-1.4.3\libs\math\include\math/vec2.h(96): message : see reference to alias template instantiation 'filament::math::details::enable_if_arithmetic_t<filament::math::half,int,int,int>' being compiled
5>.\filament-1.4.3\libs\math\include\math/vec2.h(101,15): error C2976: 'filament::math::vec2': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec2.h(97): message : see declaration of 'filament::math::vec2'
5>.\filament-1.4.3\libs\math\include\math/vec3.h(121,15): error C2976: 'filament::math::vec3': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec3.h(117): message : see declaration of 'filament::math::vec3'
5>.\filament-1.4.3\libs\math\include\math/vec4.h(119,15): error C2976: 'filament::math::vec4': too few template arguments
5>.\filament-1.4.3\libs\math\include\math/vec4.h(115): message : see declaration of 'filament::math::vec4'

### PR DESCRIPTION
**Pull request by bejado**
The latest version of MSVC appears to not allow `std::is_arithmetic` specializations for custom types. This is the best workaround I can think of at the moment.

Fixes #1939

### CODE REVIEW

File: libs/math/include/math/TVecHelpers.h [hunk 1]
```diff
@@ -27,6 +27,20 @@
...
+// filament::math::half, so we're forced to create own is_arithmetic here and specialize it inside
+// of half.h.
+template<typename T>
+struct is_arithmetic : std::integral_constant<bool,
+        std::is_integral<T>::value || std::is_floating_point<T>::value> {
+};
+
+}
+}
+
```
Comment (pixelflinger) [inline libs/math/include/math/TVecHelpers.h]: could you move that into math/compiler.h instead.

File: libs/math/include/math/half.h [hunk 2]
```diff
@@ -22,6 +22,7 @@
 #include <type_traits>
 
 #include <math/compiler.h>
+#include <math/TVecHelpers.h>
```
Comment (pixelflinger) [inline libs/math/include/math/half.h]: include comiler.h instead
