### PR TITLE
a way to keep the content of custom RenderTarget attachments

### LINKED ISSUE #3962: Can't sample depth texture in OpenGL on Mac
**Describe the bug**
When I render to a `RenderTarget` with a sample-able depth texture attached, I can successfully sample from the depth texture using Metal but not OpenGL.

**To Reproduce**
1. Uncompress the attached Xcode project on a Mac.
2. Open the project in Xcode.
3. Edit the file "proj.xcconfig" and change FILAMENT_REPO to the full path to the Filament repository on your computer.
4. Set the target pop-up menu at the top of the project window to "DR-OpenGL".
5. Build and run.

[DepthReader.zip](https://github.com/google/filament/files/6526906/DepthReader.zip)

**Expected behavior**
I expected a depth buffer display something like what is produced by the Metal target of the project:

**Actual behavior**
I see solid red.

**Screenshots**

*Metal output*
depth display in Metal

*OpenGL output*
depth display in OpenGL

**Desktop:**
 - OS: macOS 11.4 Beta (20F5055c)
 - GPU: Radeon Pro 560X 4 GB
 - Backend: OpenGL

**Additional Context:**

Previous discussion #3934

### PR DESCRIPTION
**Pull request by pixelflinger**
Until now, all attachments of RenderTarget beyond COLOR0 were discarded
after rendering.

With this change, attachment whose texture has the SAMPLEABLE usage
bit set will be kept.

Fixes #3962

### CODE REVIEW

File: filament/src/Renderer.cpp [hunk 1]
```diff
@@ -306,15 +300,40 @@ void FRenderer::renderJob(ArenaScope& arena, FView& view) {
...
+    }
+
     const float4 clearColor = mClearOptions.clearColor;
+    const TargetBufferFlags clearFlags = mClearFlags;
+    const TargetBufferFlags discardStartFlags = mDiscardStartFlags;
+    TargetBufferFlags keepOverrideEndFlags = TargetBufferFlags::NONE;
+
+    if (currentRenderTarget) {
+        // For custom RenderTarget, we look at each attachment flag and if they have their
+        // SAMPLEABLE usage bit set, we assume they most not be discarded after the render pass.
```
Comment (prideout) [inline filament/src/Renderer.cpp:321]:
```suggestion
        // SAMPLEABLE usage bit set, we assume they must not be discarded after the render pass.
```

File: filament/src/Renderer.cpp [hunk 2]
```diff
@@ -306,15 +300,40 @@ void FRenderer::renderJob(ArenaScope& arena, FView& view) {
...
+        // "+1" to the cound for the DEPTH attachment (we don't have stencil for the public RenderTarget)
```
Comment (prideout) [inline filament/src/Renderer.cpp:322]:
```suggestion
        // "+1" to the count for the DEPTH attachment (we don't have stencil for the public RenderTarget)
```

**Review by prideout — APPROVED** [review]
minor typos

**Review by romainguy — APPROVED** [review]
