### PR TITLE
vk: fix crash when resizing

### LINKED ISSUE #9718: Application crashes on window resize when using vulkan api
**Describe the bug**
Application crashes on window resize when using vulkan api
On OpenGL not crashing

**To Reproduce**
1. Run gltf_viewer.exe -a vulkan
2. Resize window
3. App crashed

**Expected behavior**
Window resized and app not crashed

**Video**
https://github.com/user-attachments/assets/81796617-3557-48bf-aae7-0fd0cfe326d0

**Logs**
```
FEngine (64 bits) created at 0000026392E98A20 (threading is enabled)
Vulkan device driver: AMD proprietary driver 26.1.1 (LLPC)
Selected physical device 'AMD Radeon RX 9070 XT' from 2 physical devices. (vendor 0x1002, device 0x7550, driver 0x800175, api 1.4)
Backend feature level: 3
FEngine feature level: 3
Requested linear format but KTX contains a sRGB format.
Requested linear format but KTX contains a sRGB format.
Texture Decoder has 14 background threads.
vkCreateSwapchain: 1024x640, VK_FORMAT_R8G8B8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, swapchain-size=3, identity-transform=true, depth=VK_FORMAT_D32_SFLOAT_S8_UINT, protected=false
vkCreateSwapchain: 1180x640, VK_FORMAT_R8G8B8A8_UNORM, VK_COLOR_SPACE_SRGB_NONLINEAR_KHR, swapchain-size=3, identity-transform=true, depth=VK_FORMAT_D32_SFLOAT_S8_UINT, protected=false
```

**Desktop (please complete the following information):**
 - OS: Windows 11 25H2
 - GPU: AMD Radeon 9070XT
 - Backend: Vulkan

**Additional context**

### PR DESCRIPTION
**Pull request by poweifeng**
The problem is that we might flush when resizing happens. So we need to ask for the command buffer "after" the resize/acquire swapchain logic.

Fixes #9718

### CODE REVIEW

File: filament/backend/src/vulkan/VulkanDriver.cpp [hunk 1]
```diff
@@ -1930,6 +1927,9 @@ void VulkanDriver::beginRenderPass(Handle<HwRenderTarget> rth, const RenderPassP
         }
     }
 
+    VulkanCommandBuffer* commandBuffer = rt->isProtected() ?
```
Comment (rafadevai) [inline filament/backend/src/vulkan/VulkanDriver.cpp]: add a comment why this has to be after the swapchain acquire

Comment (poweifeng) [reply filament/backend/src/vulkan/VulkanDriver.cpp]: done
