### PR TITLE
Fix Metal error when sampler has not been bound

### LINKED ISSUE #1209: Metal backend on iOS seems to be crashing with ubershader material provider
I am following the sample code related to loading GLTF models directly on my iOS device. From what I have found so far the only way to do this on mobile is to use createUbershaderLoader and pass the result to the AssetLoader. The other option - createMaterialGenerator seems to be available only on the desktop targets. 

Using the ubershader with OpenGL backend works fine, but when I switch to Metal I get a flavor of this assert and then a crash:

validateFunctionArguments:3531: failed assertion `Fragment Function(main0): missing sampler binding at index 6 for materialParams_baseColorMapSmplr[0].'

The problem seems to be unrelated to specific gltf file. I tried with several - I got the same assert.

The Metal backend works fine with .filamesh and .filamat files but In this case I am not using  the ubershader and the asset loader.

So my question is: is this a known bug with the uberhader and Metal and is there any workaround which doesn't involve falling back to using .filamesh and .filamat data?

 - Device: iPhone XR
 - OS: iOS 12.1
 - Backend: Metal

[cubo.zip](https://github.com/google/filament/files/3200498/cubo.zip)

### PR DESCRIPTION
**Pull request by bejado**
Fixes #1209

### CODE REVIEW

File: filament/backend/src/metal/MetalDriver.mm [hunk 1]
```diff
@@ -824,6 +824,15 @@
         samplersToBind[binding] = samplerState;
     });
 
+    // Assign a default sampler to empty slots, in case Filament hasn't bound all samplers.
+    // Metal requires all samplers referenced in shaders to be bound.
+    for (auto& sampler : samplersToBind) {
+        if (!sampler) {
+            static SamplerParams defaultSampler;
```
Comment (pixelflinger) [inline filament/backend/src/metal/MetalDriver.mm]: I wouldn't make it static here -- it's probably more costly than a regular stack object. In fact, I think you can just write `.getOrCreateState({})`

Comment (bejado) [reply filament/backend/src/metal/MetalDriver.mm]: Good call
