### PR TITLE
gltfio: allow for multiple color attributes

### LINKED ISSUE #8396: GLB model with two Face Corner Byte Color Attributes crashes VertexBuilder on iOS
⚠️ **Issues not using this template will be systematically closed.**

**Describe the bug**
When loading a model with **two face corner byte color attributes**, Filament crashes with **PreconditionPanic** in the **VertexBuffer::Builder::build** function.

**To Reproduce**
1. Use [React Native Filament](https://github.com/margelo/react-native-filament) 1.6.1 which wraps [filament @ 3ca9b9c](https://github.com/google/filament/tree/3ca9b9cd0fdb6435af3a084813edd6ead8abc2b8). In theory this should also apply to directly using Filament.

2. Load attached model which has two face corner byte color attributes

3. Observe crash

**Expected behavior**
The model should load and be displayed.

**Screenshots**

Image
Inspecting the model using Blender we can see the two Byte Color attributes.

**Logs**
Crash as observed from iOS Simulator:

```log

Incident Identifier: 2E712926-E92D-43EB-AD8C-30986AF675F4
CrashReporter Key:   245733B2-5A50-B576-56D3-94AA9BC07367
Hardware Model:      Mac16,8
Process:             omnirn [52470]
Path:                /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/omnirn
Identifier:          com.anonymous.omnirn
Version:             1.0.0 (1)
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd_sim [1430]
Coalition:           com.apple.CoreSimulator.SimDevice.E6C708C6-2D4D-4F37-B8DC-1A633B434A83 [1211]
Responsible Process: SimulatorTrampoline [1261]

Date/Time:           2025-01-29 12:35:24.1657 +0100
Launch Time:         2025-01-29 11:42:58.7646 +0100
OS Version:          macOS 15.1 (24B2082)
Release Type:        User
Report Version:      104

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Termination Reason: SIGNAL 6 Abort trap: 6
Terminating Process: omnirn [52470]

Triggered by Thread:  10

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   GraphicsServices              	       0x1905e5b10 GSEventRunModal + 160
8   UIKitCore                     	       0x185b319dc -[UIApplication _run] + 796
9   UIKitCore                     	       0x185b35bd4 UIApplicationMain + 124
10  omnirn.debug.dylib            	       0x108a362c8 __debug_main_executable_dylib_entry_point + 96 (main.m:7)
11  dyld_sim                      	       0x101315410 start_sim + 20
12  dyld                          	       0x1011f2274 start + 2840

Thread 1:: com.apple.uikit.eventfetch-thread
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   Foundation                    	       0x180f1f438 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   Foundation                    	       0x180f1f658 -[NSRunLoop(NSRunLoop) runUntilDate:] + 60
9   UIKitCore                     	       0x185bdf284 -[UIEventFetcher threadMain] + 404
10  Foundation                    	       0x180f46280 __NSThread__start__ + 720
11  libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
12  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 2:: com.facebook.react.runtime.JavaScript
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   omnirn.debug.dylib            	       0x109733d8c +[RCTJSThreadManager runRunLoop] + 292 (RCTJSThreadManager.mm:102)
8   Foundation                    	       0x180f46280 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 3:: hades
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10272f1a0 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10272f104 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 4:: com.apple.CFStream.LegacyThread
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   CoreFoundation                	       0x18043ae9c _legacyStreamRunLoop_workThread + 260
8   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
9   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 5:: com.facebook.SocketRocket.NetworkThread
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   Foundation                    	       0x180f1f438 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
8   omnirn.debug.dylib            	       0x109ad466c -[SRRunLoopThread main] + 260 (SRRunLoopThread.m:71)
9   Foundation                    	       0x180f46280 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 6:: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   CFNetwork                     	       0x184a03d64 +[__CFN_CoreSchedulingSetRunnable _run:] + 372
8   Foundation                    	       0x180f46280 __NSThread__start__ + 720
9   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
10  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 7:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	       0x10107f700 __select + 8
1   CoreFoundation                	       0x18042b518 __CFSocketManager + 676
2   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
3   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 8:
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a56e11c void std::__1::condition_variable::wait<RNWorklet::DispatchQueue::dispatch_thread_handler()::$_0>(std::__1::unique_lock<std::__1::mutex>&, RNWorklet::DispatchQueue::dispatch_thread_handler()::$_0) + 64 (condition_variable.h:146)
4   omnirn.debug.dylib            	       0x10a56dd90 RNWorklet::DispatchQueue::dispatch_thread_handler() + 84 (WKTDispatchQueue.cpp:49)
5   omnirn.debug.dylib            	       0x10a56e818 decltype(*std::declval<RNWorklet::DispatchQueue*>().*std::declval<void (RNWorklet::DispatchQueue::*)()>()()) std::__1::__invoke[abi:de180100]<void (RNWorklet::DispatchQueue::*)(), RNWorklet::DispatchQueue*, void>(void (RNWorklet::DispatchQueue::*&&)(), RNWorklet::DispatchQueue*&&) + 132 (invoke.h:312)
6   omnirn.debug.dylib            	       0x10a56e788 void std::__1::__thread_execute[abi:de180100]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (RNWorklet::DispatchQueue::*)(), RNWorklet::DispatchQueue*, 2ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (RNWorklet::DispatchQueue::*)(), RNWorklet::DispatchQueue*>&, std::__1::__tuple_indices<2ul>) + 48 (thread.h:199)
7   omnirn.debug.dylib            	       0x10a56e434 void* std::__1::__thread_proxy[abi:de180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (RNWorklet::DispatchQueue::*)(), RNWorklet::DispatchQueue*>>(void*) + 84 (thread.h:208)
8   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
9   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 9:: hades
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10272f1a0 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10272f104 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 10 Crashed:: filament.render.queue
0   libsystem_kernel.dylib        	       0x10107d008 __pthread_kill + 8
1   libsystem_pthread.dylib       	       0x100fff408 pthread_kill + 256
2   libsystem_c.dylib             	       0x1801704ec abort + 104
3   omnirn.debug.dylib            	       0x10a883268 utils::TPanic<utils::PreconditionPanic>::panic(char const*, char const*, int, char const*, ...) + 148
4   omnirn.debug.dylib            	       0x109c5386c filament::VertexBuffer::Builder::build(filament::Engine&) + 368
5   omnirn.debug.dylib            	       0x109c7c9f4 filament::gltfio::FAssetLoader::createPrimitive(cgltf_primitive const&, char const*, filament::gltfio::Primitive*, filament::gltfio::FFilamentAsset*) + 4308
6   omnirn.debug.dylib            	       0x109c7a72c filament::gltfio::FAssetLoader::createPrimitives(cgltf_node const*, char const*, filament::gltfio::FFilamentAsset*) + 280
7   omnirn.debug.dylib            	       0x109c7a4c8 filament::gltfio::FAssetLoader::recursePrimitives(cgltf_node const*, filament::gltfio::FFilamentAsset*) + 108
8   omnirn.debug.dylib            	       0x109c78e54 filament::gltfio::FAssetLoader::createRootAsset(cgltf_data const*) + 880
9   omnirn.debug.dylib            	       0x109c789d0 filament::gltfio::FAssetLoader::createInstancedAsset(unsigned char const*, unsigned int, filament::gltfio::FilamentInstance**, unsigned long) + 188
10  omnirn.debug.dylib            	       0x109c7e540 filament::gltfio::AssetLoader::createAsset(unsigned char const*, unsigned int) + 24
11  omnirn.debug.dylib            	       0x10a24e9e4 margelo::EngineImpl::loadAsset(std::__1::shared_ptr<margelo::FilamentBuffer>) + 164 (RNFEngineImpl.cpp:234)
12  omnirn.debug.dylib            	       0x10a2cd790 margelo::EngineWrapper::loadAsset(std::__1::shared_ptr<margelo::FilamentBuffer>) + 92 (RNFEngineWrapper.cpp:103)
13  omnirn.debug.dylib            	       0x10a2e08a4 facebook::jsi::Value margelo::HybridObject::callMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>, 0ul>(margelo::EngineWrapper*, std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), facebook::jsi::Runtime&, facebook::jsi::Value const*, std::__1::integer_sequence<unsigned long, 0ul>) + 196 (RNFHybridObject.h:91)
14  omnirn.debug.dylib            	       0x10a2e07d4 std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const + 84 (RNFHybridObject.h:107)
15  omnirn.debug.dylib            	       0x10a2e0774 decltype(std::declval<margelo::EngineWrapper>()(std::declval<facebook::jsi::Runtime&>(), std::declval<facebook::jsi::Value const&>(), std::declval<facebook::jsi::Value const*>(), std::declval<unsigned long>())) std::__1::__invoke[abi:de180100]<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(margelo::EngineWrapper&&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 72 (invoke.h:344)
16  omnirn.debug.dylib            	       0x10a2e06fc facebook::jsi::Value std::__1::__invoke_void_return_wrapper<facebook::jsi::Value, false>::__call[abi:de180100]<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long>(std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)&, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 64 (invoke.h:411)
17  omnirn.debug.dylib            	       0x10a2e06b0 std::__1::__function::__alloc_func<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long), std::__1::allocator<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()[abi:de180100](facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 72 (function.h:169)
18  omnirn.debug.dylib            	       0x10a2df690 std::__1::__function::__func<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long), std::__1::allocator<std::__1::function<facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)> margelo::HybridObject::createHybridMethod<margelo::EngineWrapper, std::__1::shared_ptr<margelo::FilamentAssetWrapper>, std::__1::shared_ptr<margelo::FilamentBuffer>>(std::__1::shared_ptr<margelo::FilamentAssetWrapper> (margelo::EngineWrapper::*)(std::__1::shared_ptr<margelo::FilamentBuffer>), margelo::EngineWrapper*)::'lambda'(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>, facebook::jsi::Value (facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long)>::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*&&, unsigned long&&) + 68 (function.h:311)
19  hermes                        	       0x10259f478 facebook::hermes::HermesRuntimeImpl::HFContext::func(void*, hermes::vm::Runtime&, hermes::vm::NativeArgs) + 536
20  hermes                        	       0x10264bbb0 hermes::vm::NativeFunction::_nativeCall(hermes::vm::NativeFunction*, hermes::vm::Runtime&) + 144
21  hermes                        	       0x102665c80 hermes::vm::CallResult<hermes::vm::HermesValue, (hermes::vm::detail::CallResultSpecialize)2> hermes::vm::Interpreter::interpretFunction<false, false>(hermes::vm::Runtime&, hermes::vm::InterpreterState&) + 2312
22  hermes                        	       0x102665344 hermes::vm::Runtime::interpretFunctionImpl(hermes::vm::CodeBlock*) + 132
23  hermes                        	       0x10264be84 hermes::vm::JSFunction::_callImpl(hermes::vm::Handle<hermes::vm::Callable>, hermes::vm::Runtime&) + 40
24  hermes                        	       0x102597860 facebook::hermes::HermesRuntimeImpl::call(facebook::jsi::Function const&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 744
25  omnirn.debug.dylib            	       0x108b582dc facebook::jsi::Function::callWithThis(facebook::jsi::Runtime&, facebook::jsi::Object const&, facebook::jsi::Value const*, unsigned long) const + 112 (jsi-inl.h:285)
26  omnirn.debug.dylib            	       0x10a5d0ee8 RNWorklet::JsiWorklet::call(std::__1::shared_ptr<facebook::jsi::Function>, facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 428 (WKTJsiWorklet.h:219)
27  omnirn.debug.dylib            	       0x10a5d07ec RNWorklet::WorkletInvoker::call(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) + 248 (WKTJsiWorklet.h:369)
28  omnirn.debug.dylib            	       0x10a5da6ac RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)::operator()(facebook::jsi::Runtime&) + 208 (WKTJsiWorkletContext.cpp:353)
29  omnirn.debug.dylib            	       0x10a5da5d0 decltype(std::declval<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)&>()(std::declval<facebook::jsi::Runtime&>())) std::__1::__invoke[abi:de180100]<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)&, facebook::jsi::Runtime&>(RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)&, facebook::jsi::Runtime&) + 32 (invoke.h:344)
30  omnirn.debug.dylib            	       0x10a5da580 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de180100]<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)&, facebook::jsi::Runtime&>(RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)&, facebook::jsi::Runtime&) + 32 (invoke.h:419)
31  omnirn.debug.dylib            	       0x10a5da554 std::__1::__function::__alloc_func<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&), std::__1::allocator<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)>, void (facebook::jsi::Runtime&)>::operator()[abi:de180100](facebook::jsi::Runtime&) + 36 (function.h:169)
32  omnirn.debug.dylib            	       0x10a5d922c std::__1::__function::__func<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&), std::__1::allocator<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda0'(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>)::operator()(facebook::jsi::Runtime&, std::__1::shared_ptr<RNWorklet::PromiseParameter>) const::'lambda'(facebook::jsi::Runtime&)>, void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) + 36 (function.h:311)
33  omnirn.debug.dylib            	       0x108b7e300 std::__1::__function::__value_func<void (facebook::jsi::Runtime&)>::operator()[abi:de180100](facebook::jsi::Runtime&) const + 76 (function.h:428)
34  omnirn.debug.dylib            	       0x108b7e1c4 std::__1::function<void (facebook::jsi::Runtime&)>::operator()(facebook::jsi::Runtime&) const + 32 (function.h:981)
35  omnirn.debug.dylib            	       0x10a5d6b00 RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)::operator()(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&) const + 36 (WKTJsiWorkletContext.cpp:310)
36  omnirn.debug.dylib            	       0x10a5d6ad0 decltype(std::declval<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)&>()(std::declval<RNWorklet::JsiWorkletContext*>(), std::declval<facebook::jsi::Runtime&>())) std::__1::__invoke[abi:de180100]<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)&, RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&>(RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)&, RNWorklet::JsiWorkletContext*&&, facebook::jsi::Runtime&) + 44 (invoke.h:344)
37  omnirn.debug.dylib            	       0x10a5d6a74 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de180100]<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)&, RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&>(RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)&, RNWorklet::JsiWorkletContext*&&, facebook::jsi::Runtime&) + 40 (invoke.h:419)
38  omnirn.debug.dylib            	       0x10a5d6a40 std::__1::__function::__alloc_func<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&), std::__1::allocator<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>, void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>::operator()[abi:de180100](RNWorklet::JsiWorkletContext*&&, facebook::jsi::Runtime&) + 44 (function.h:169)
39  omnirn.debug.dylib            	       0x10a5d581c std::__1::__function::__func<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&), std::__1::allocator<RNWorklet::JsiWorkletContext::createCallInContext(facebook::jsi::Runtime&, facebook::jsi::Value const&, RNWorklet::JsiWorkletContext*)::$_0::operator()(facebook::jsi::Runtime&, facebook::jsi::Value const&, facebook::jsi::Value const*, unsigned long) const::'lambda'(std::__1::function<void (facebook::jsi::Runtime&)>&&)::operator()(std::__1::function<void (facebook::jsi::Runtime&)>&&) const::'lambda'(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>, void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>::operator()(RNWorklet::JsiWorkletContext*&&, facebook::jsi::Runtime&) + 44 (function.h:311)
40  omnirn.debug.dylib            	       0x10a5c5670 std::__1::__function::__value_func<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>::operator()[abi:de180100](RNWorklet::JsiWorkletContext*&&, facebook::jsi::Runtime&) const + 84 (function.h:428)
41  omnirn.debug.dylib            	       0x10a5c5610 std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>::operator()(RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&) const + 44 (function.h:981)
42  omnirn.debug.dylib            	       0x10a5c55a8 RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0::operator()() const + 112 (WKTJsiWorkletContext.cpp:154)
43  omnirn.debug.dylib            	       0x10a5c552c decltype(std::declval<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0&>()()) std::__1::__invoke[abi:de180100]<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0&>(RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0&) + 24 (invoke.h:344)
44  omnirn.debug.dylib            	       0x10a5c54e4 void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:de180100]<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0&>(RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0&) + 24 (invoke.h:419)
45  omnirn.debug.dylib            	       0x10a5c54c0 std::__1::__function::__alloc_func<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0, std::__1::allocator<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0>, void ()>::operator()[abi:de180100]() + 28 (function.h:169)
46  omnirn.debug.dylib            	       0x10a5c4128 std::__1::__function::__func<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0, std::__1::allocator<RNWorklet::JsiWorkletContext::invokeOnWorkletThread(std::__1::function<void (RNWorklet::JsiWorkletContext*, facebook::jsi::Runtime&)>&&)::$_0>, void ()>::operator()() + 28 (function.h:311)
47  omnirn.debug.dylib            	       0x108b8041c std::__1::__function::__value_func<void ()>::operator()[abi:de180100]() const + 68 (function.h:428)
48  omnirn.debug.dylib            	       0x108b803cc std::__1::function<void ()>::operator()() const + 24 (function.h:981)
49  omnirn.debug.dylib            	       0x10a41db60 margelo::NSThreadDispatcher::run(std::__1::function<void ()>&&, bool)::$_0::operator()() const + 24 (RNFNSThreadDispatcher.mm:35)
50  omnirn.debug.dylib            	       0x10a41db3c invocation function for block in margelo::NSThreadDispatcher::run(std::__1::function<void ()>&&, bool) + 28 (RNFNSThreadDispatcher.mm:33)
51  Foundation                    	       0x180f465ec __NSThreadPerformPerform + 124
52  CoreFoundation                	       0x18041d294 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
53  CoreFoundation                	       0x18041d1dc __CFRunLoopDoSource0 + 172
54  CoreFoundation                	       0x18041c940 __CFRunLoopDoSources0 + 232
55  CoreFoundation                	       0x180416e84 __CFRunLoopRun + 788
56  CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
57  Foundation                    	       0x180f1f438 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 208
58  Foundation                    	       0x180f1f608 -[NSRunLoop(NSRunLoop) run] + 60
59  omnirn.debug.dylib            	       0x10a41d830 invocation function for block in margelo::NSThreadDispatcher::NSThreadDispatcher(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 132 (RNFNSThreadDispatcher.mm:21)
60  Foundation                    	       0x180f46280 __NSThread__start__ + 720
61  libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
62  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 11:: hades
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10272f1a0 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10272f104 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 12:: hades
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   hermes                        	       0x10272f1a0 hermes::vm::HadesGC::Executor::worker() + 112
4   hermes                        	       0x10272f104 void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, hermes::vm::HadesGC::Executor::Executor()::'lambda'()>>(void*) + 44
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 13:: com.mapbox.common.Unspecified Worker 1
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   MapboxCommon                  	       0x101b13a48 0x10198c000 + 1604168
4   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
5   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 14:: com.mapbox.common.Unspecified Worker 1
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   MapboxCommon                  	       0x101b13a48 0x10198c000 + 1604168
4   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
5   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 15:: com.mapbox.common.location.sharedRunloop
0   libsystem_kernel.dylib        	       0x101075290 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x1010866c4 mach_msg2_internal + 76
2   libsystem_kernel.dylib        	       0x10107d3f4 mach_msg_overwrite + 536
3   libsystem_kernel.dylib        	       0x1010755cc mach_msg + 20
4   CoreFoundation                	       0x18041cad0 __CFRunLoopServiceMachPort + 156
5   CoreFoundation                	       0x180416ff8 __CFRunLoopRun + 1160
6   CoreFoundation                	       0x1804166f4 CFRunLoopRunSpecific + 552
7   CoreFoundation                	       0x180417624 CFRunLoopRun + 60
8   MapboxCommon                  	       0x101b9ad3c 0x10198c000 + 2157884
9   Foundation                    	       0x180f46280 __NSThread__start__ + 720
10  libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
11  libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 16:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0

Thread 17:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0

Thread 18:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0

Thread 19:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0

Thread 20:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0

Thread 21:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 22:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 23:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 24:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 25:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 26:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 27:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 28:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 29:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 30:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 31:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 32:: JobSystem::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x10a880308 utils::JobSystem::loop(utils::JobSystem::ThreadState*) + 180
4   omnirn.debug.dylib            	       0x10a8813f0 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (utils::JobSystem::*)(utils::JobSystem::ThreadState*) noexcept, utils::JobSystem*, utils::JobSystem::ThreadState*>>(void*) + 68
5   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
6   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 33:: FEngine::loop
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x109b76e14 filament::backend::CommandBufferQueue::waitForCommands() const + 96
4   omnirn.debug.dylib            	       0x109c3b34c filament::FEngine::loop() + 296
5   omnirn.debug.dylib            	       0x109c3eda8 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, int (filament::FEngine::*)(), filament::FEngine*>>(void*) + 64
6   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
7   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 34:
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x109b7981c void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, filament::backend::DriverBase::DriverBase()::$_0>>(void*) + 140
4   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
5   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 35:
0   libsystem_kernel.dylib        	       0x10107872c __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x100fffc98 _pthread_cond_wait + 1192
2   libc++.1.dylib                	       0x18030529c std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 24
3   omnirn.debug.dylib            	       0x109b78548 void* std::__1::__thread_proxy[abi:nn180100]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, filament::backend::CompilerThreadPool::init(unsigned int, utils::Invocable<void ()>&&, utils::Invocable<void ()>&&)::$_0>>(void*) + 268
4   libsystem_pthread.dylib       	       0x100fff6f8 _pthread_start + 104
5   libsystem_pthread.dylib       	       0x100ffa940 thread_start + 8

Thread 36:
0   libsystem_pthread.dylib       	       0x100ffa92c start_wqthread + 0


Thread 10 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000000   x1: 0x0000000000000000   x2: 0x0000000000000000   x3: 0x0000000000000000
    x4: 0x000000010add6c6c   x5: 0x000000016f824320   x6: 0x000000000000000a   x7: 0x0000000000000000
    x8: 0x000000016f827000   x9: 0x9010a4d140200112  x10: 0x0000000000000000  x11: 0x0000000000000002
   x12: 0x0000000000000000  x13: 0x0000000000000002  x14: 0x0000000000000000  x15: 0x0000000000000000
   x16: 0x0000000000000148  x17: 0x0000000000000002  x18: 0x0000000000000000  x19: 0x0000000000000006
   x20: 0x000000000000fe03  x21: 0x000000016f8270e0  x22: 0x0000000000000037  x23: 0x0000000000000000
   x24: 0x0000000000000001  x25: 0x0000000000000005  x26: 0x0000000000000004  x27: 0x00006000070017c0
   x28: 0x000000012e32afa8   fp: 0x000000016f824320   lr: 0x0000000100fff408
    sp: 0x000000016f824300   pc: 0x000000010107d008 cpsr: 0x40000000
   far: 0x0000000000000000  esr: 0x56000080  Address size fault

Binary Images:
       0x1011ec000 -        0x10126ffff dyld (*) <5ca59b26-65ac-3e9a-89bd-3ffd45a097c2> /usr/lib/dyld
       0x100fa0000 -        0x100fa3fff com.anonymous.omnirn (1.0.0) <1285679f-e9f7-38e4-88b9-658e25488354> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/omnirn
       0x101314000 -        0x101357fff dyld_sim (*) <e71713fd-bf2a-3d11-a0e8-94488ca5d57a> /Volumes/VOLUME/*/dyld_sim
       0x108a30000 -        0x10af57fff omnirn.debug.dylib (*) <6ade3850-9eed-3789-8528-c7db69760cd1> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/omnirn.debug.dylib
       0x10198c000 -        0x101eaffff com.mapbox.common (24.8.0) <db57c4e7-64e8-3229-9f20-e0e6d89b6849> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/Frameworks/MapboxCommon.framework/MapboxCommon
       0x1031cc000 -        0x103c07fff com.mapbox.maps (11.8.0) <6060ce15-60b2-3584-99df-453ea4b7a478> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/Frameworks/MapboxCoreMaps.framework/MapboxCoreMaps
       0x104460000 -        0x1049c7fff org.cocoapods.MapboxMaps (11.8.0) <d7ad7e95-10ca-3475-803a-0e81ffde53e3> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/Frameworks/MapboxMaps.framework/MapboxMaps
       0x1010ec000 -        0x101157fff org.cocoapods.Turf (3.0.0) <28c359a7-543e-3b3f-86e1-9fe5fb6bb6c8> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/Frameworks/Turf.framework/Turf
       0x10258c000 -        0x1028fbfff dev.hermesengine.iphonesimulator (0.12.0) <5239edf2-abe9-3614-8b59-2091cdb0d87d> /Users/USER/Library/Developer/CoreSimulator/Devices/E6C708C6-2D4D-4F37-B8DC-1A633B434A83/data/Containers/Bundle/Application/3315FD92-29F0-4D04-B4EE-410459781AB4/omnirn.app/Frameworks/hermes.framework/hermes
       0x101054000 -        0x10105bfff libsystem_platform.dylib (*) <6b034656-50dd-3f65-8f4e-50a45beb3397> /usr/lib/system/libsystem_platform.dylib
       0x101074000 -        0x1010affff libsystem_kernel.dylib (*) <69036356-4efc-3e8c-bdc5-1d867464a72b> /usr/lib/system/libsystem_kernel.dylib
       0x100ff8000 -        0x101007fff libsystem_pthread.dylib (*) <3e98cd5c-75f3-3315-a213-731b05c42112> /usr/lib/system/libsystem_pthread.dylib
       0x1015dc000 -        0x1015e7fff libobjc-trampolines.dylib (*) <a31fa6bc-f00c-3232-9da8-4e5d7922ed9a> /Volumes/VOLUME/*/libobjc-trampolines.dylib
       0x18038d000 -        0x18075afff com.apple.CoreFoundation (6.9) <e965e773-9803-3e02-8243-5cb8f4365f11> /Volumes/VOLUME/*/CoreFoundation.framework/CoreFoundation
       0x1905e2000 -        0x1905eafff com.apple.GraphicsServices (1.0) <9c82f9b7-b20c-3255-80a1-c4a1e74ef754> /Volumes/VOLUME/*/GraphicsServices.framework/GraphicsServices
       0x184cd3000 -        0x186a10fff com.apple.UIKitCore (1.0) <24ff1688-4bc4-3da8-8f17-c73d22f96263> /Volumes/VOLUME/*/UIKitCore.framework/UIKitCore
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x1807da000 -        0x181416fff com.apple.Foundation (6.9) <b8e40415-c88f-3ceb-971c-82679743b9be> /Volumes/VOLUME/*/Foundation.framework/Foundation
       0x1802e5000 -        0x180367ff3 libc++.1.dylib (*) <924c08a7-28c0-3c03-87e9-197d387ee4c9> /Volumes/VOLUME/*/libc++.1.dylib
       0x1847fa000 -        0x184b7bfff com.apple.CFNetwork (1.0) <28f30cff-18c1-3fb9-b1e9-e185e004ac74> /Volumes/VOLUME/*/CFNetwork.framework/CFNetwork
       0x1800fd000 -        0x180178ff3 libsystem_c.dylib (*) <3e34edd7-d111-3f74-bacd-9a4e955d66e6> /Volumes/VOLUME/*/libsystem_c.dylib

EOF
```

**Desktop (please complete the following information):**
 - OS: iOS 18.2 Simulator on M4 Pro Sequoia 15.1
 - GPU: see above
 - Backend: Metal

**Additional context**
Testing file attached. Removing one of attributes solves crash. Import/Export via Blender 4.3.2
[avatar_armature_only.glb.zip](https://github.com/user-attachments/files/18587253/avatar_armature_only.glb.zip)

### PR DESCRIPTION
**Pull request by poweifeng**
We are not correctly handling gltf models with multiple color attributes. Filament doesn't allow for more than one color attribute.  So we just set the additional attributes as VertexAttribute::CUSOM(N).

Also properly clean up dummy buffer.

Fixes #8396

### CODE REVIEW

File: libs/gltfio/src/AssetLoader.cpp [hunk 1]
```diff
@@ -357,6 +359,12 @@ struct FAssetLoader : public AssetLoader {
 
 FILAMENT_DOWNCAST(AssetLoader)
 
+FAssetLoader::~FAssetLoader() {
+    if (mDummyBufferObject) {
+        mEngine.destroy(mDummyBufferObject);
+    }
+}
```
Comment (pixelflinger) [inline libs/gltfio/src/AssetLoader.cpp:366]: was this just leaking before?  Also is it safe to do this in the FAssetLoader dtor -- i.e. is it guaranteed to be called on the correct thread?

File: libs/gltfio/src/AssetLoader.cpp [hunk 2]
```diff
@@ -1237,6 +1257,10 @@ bool FAssetLoader::createPrimitive(const cgltf_primitive& inPrim, const char* na
     if (needsDummyData) {
         const uint32_t requiredSize = sizeof(ubyte4) * vertexCount;
         if (mDummyBufferObject == nullptr || requiredSize > mDummyBufferObject->getByteCount()) {
+            if (mDummyBufferObject) {
+                mEngine.destroy(mDummyBufferObject);
+                mDummyBufferObject = nullptr;
```
Comment (pixelflinger) [inline libs/gltfio/src/AssetLoader.cpp:1262]: maybe we could factorize those 3 lines somehow, seems to be used 3 times.

File: libs/gltfio/src/AssetLoader.cpp (hunk 1 above)
Comment (poweifeng) [reply libs/gltfio/src/AssetLoader.cpp]: actually, I misread the code.  It was properly cleaned up before.  I removed all the dummy buffer changes.

**Review by pixelflinger — APPROVED** [review]
