### PR TITLE
gltfio: various improvements to skinning normalization.

### LINKED ISSUE #2714: Polly glTF model does not display correctly in WebGL environment
**Describe the bug**

I tried displaying the [Polly glTF model](https://rawcdn.githack.com/KhronosGroup/glTF-Blender-Exporter/0e23c773bf27dad67d2c25f060370d6fa012d87d/polly/project_polly.gltf) in Filament `1.7.0`.
However, after a few seconds the display goes wrong.

filament_polly_problem

**To Reproduce**
https://cx20.github.io/jsdo.it-archives/cx20/M2lx/

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser : [Chrome 83]
 - GPU: [Intel(R) UHD Graphics 617]
 - Backend: [ANGLE]

### PR DESCRIPTION
**Pull request by prideout**
- Allow JavaScript and Java / Kotlin clients to configure this setting.
- Opt in by default (this was disabled in #2621)
- Optimize large assets like Bistro by iterating through prims only when the asset actually has skins.

Fixes #2714.

### CODE REVIEW

File: libs/gltfio/src/ResourceLoader.cpp [hunk 1]
```diff
@@ -381,13 +381,19 @@ bool ResourceLoader::loadResources(FFilamentAsset* asset, bool async) {
...
-    // places, this will needlessly repeat the work. In the future we would like to remove this
-    // feature, and instead simply require correct models. See also:
-    // https://github.com/KhronosGroup/glTF-Sample-Models/issues/215
-    if (pImpl->mNormalizeSkinningWeights) {
-        normalizeSkinningWeights(asset);
+    // Normalize skinning weights, then "import" each skin into the asset by building a mapping of
+    // skins to their affected entities.
+    if (gltf->skins_count > 0) {
+        if (pImpl->mNormalizeSkinningWeights) {
+            normalizeSkinningWeights(asset);
```
Comment (romainguy) [inline libs/gltfio/src/ResourceLoader.cpp:388]: BTW if this causes performance issues we should be able to use the job system and write the code in the way that will produce vectorized code.

Comment (prideout) [reply libs/gltfio/src/ResourceLoader.cpp:388]: Yes this would be easy to do since we already use jobs for bounding boxes and tangent gen.  Something for the future.
