### PR TITLE
Move stereoscopic debug options to Settings framework

### LINKED ISSUE #7330: stereo option in ViewerGui doesn't use the Settings framework
This code

```
        StereoscopicOptions stereoOptions = mView->getStereoscopicOptions();
        ImGui::Checkbox("Instanced stereo", &stereoOptions.enabled);
        if (stereoOptions.enabled) {
            ImGui::SliderFloat("Ocular distance", &mOcularDistance, 0.0f, 10.0f);

        }
        mView->setStereoscopicOptions(stereoOptions);
```

in `ViewerGui.cpp` is wrong because it will activate stereo on the UI context (when running on Web with remote ui). Like with all other settings, stereo must use the `Settings` framework or be moved to  the `Debug` tab. However, for testing it would be much better that we can use this on devices.

### PR DESCRIPTION
**Pull request by bejado**
This also adds a public `Engine::getConfig` API, which helps simplify things.

Fixes #7330

### CODE REVIEW

File: libs/viewer/src/Settings.cpp [hunk 1]
```diff
@@ -646,6 +651,20 @@ void applySettings(Engine* engine, const ViewerOptions& settings, Camera* camera
         camera->setFocusDistance(settings.cameraFocusDistance);
     }
     engine->setAutomaticInstancingEnabled(settings.autoInstancingEnabled);
+
+    // Eyes are rendered from left-to-right, i.e., eye 0 is rendered to the left side of the
+    // window.
+    // For testing, we want to render a side-by-side layout so users can view with
+    // "cross-eyed" stereo.
+    // For cross-eyed stereo, Eye 0 is really the RIGHT eye, while Eye 1 is the LEFT eye.
```
Comment (z3moon) [inline libs/viewer/src/Settings.cpp:659]: Just curious, is there any reason why we didn't match the order of the eyes on the screen with the order of the array?

**Review by pixelflinger — CHANGES_REQUESTED** [review]
don't forget the java and js bindings.

**Review by pixelflinger — APPROVED** [review]
LGTM but needs java and js bindings.

**Review by poweifeng — APPROVED** [review]

File: libs/viewer/src/Settings.cpp (hunk 1 above)
Comment (bejado) [reply libs/viewer/src/Settings.cpp:659]: So in fact we do, and maybe my comment is a little confusing. But eye 0 is always rendered to the left side of the screen, and eye 1 is rendered to the right side:

```
0 | 1
```

What this comment alludes to, is the fact that to render [cross-eyed stereo](https://www.kula3d.com/how-to-use-the-cross-eyed-method), the left and right eyes need to be flipped.
