### PR TITLE
better handle float rendertargets

### LINKED ISSUE #1533: crash on create rendertarget on android
**Describe the bug**
crash on creating render target on some huawei android device. the log below

Filament: OpenGL framebuffer error 0x8cd6 (GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT) in "void filament::OpenGLDriver::framebufferTexture(const backend::TargetBufferInfo &, const filament::OpenGLDriver::GLRenderTarget *, GLenum)" at line 1216
libc++abi: terminating

our code below:
color = Texture.Builder()
                    .width(width)
                    .height(height)
                    .levels(1)
                    .usage(Texture.Usage.COLOR_ATTACHMENT or Texture.Usage.SAMPLEABLE)
                    .format(Texture.InternalFormat.RGBA16F)
                    .build(engine)
            view.isPostProcessingEnabled = true
            if ( hasDepth){
                val depthbit:Texture.InternalFormat
                if ( depthBufferBits == 32){
                    depthbit = Texture.InternalFormat.DEPTH32F
                }
                else if ( depthBufferBits == 24){
                    depthbit = Texture.InternalFormat.DEPTH24
                }
                else{
                    depthbit = Texture.InternalFormat.DEPTH16
                }
                depth = Texture.Builder()
                        .width(width).height(height).levels(1)
                        .usage(Texture.Usage.DEPTH_ATTACHMENT)
                        .format(depthbit)
                        .build(engine)
               view.renderTarget = RenderTarget.Builder()
                       .texture(RenderTarget.AttachmentPoint.COLOR, color)
                       .texture(RenderTarget.AttachmentPoint.DEPTH, depth)
                       .build(engine)
                view.antiAliasing = View.AntiAliasing.FXAA
                view.sampleCount = 4
                view.toneMapping = View.ToneMapping.ACES

            }
            else{
                view.toneMapping = View.ToneMapping.ACES

                depth = null
               view.sampleCount = 1;
               view.renderTarget = RenderTarget.Builder()
                       .texture(RenderTarget.AttachmentPoint.COLOR, color)
                       .build(engine)

           }

### PR DESCRIPTION
**Pull request by pixelflinger**
some driver don't support all float buffers as rendertarget, so we
improve the backends (opengl in this PR) to return what it actually
supports and we update the client (filament) to take that into
account when making decisions.

fixes #1533

### CODE REVIEW

File: filament/backend/src/opengl/OpenGLDriver.cpp [hunk 1]
```diff
@@ -1732,18 +1740,25 @@ bool OpenGLDriver::isRenderTargetFormatSupported(TextureFormat format) {
...
-
-        // Float formats from GL_EXT_color_buffer_float, assumed supported.
         case TextureFormat::R16F:
         case TextureFormat::RG16F:
         case TextureFormat::RGBA16F:
+            return ext.EXT_color_buffer_float || ext.EXT_color_buffer_half_float;
+
+        // RGB32F and RGB16F are only supported with EXT_color_buffer_half_float
+        case TextureFormat::RGB16F:
+        case TextureFormat::RGB32F:
```
Comment (romainguy) [inline filament/backend/src/opengl/OpenGLDriver.cpp]: RGB32F is not given by EXT_color_buffer_half_float.
