### PR TITLE
Fix memory corruption in FScene

### LINKED ISSUE #6275: [iOS Metal] "malloc: Heap corruption" randomly occurring when opening and exiting Filament view with glb assets
**Describe the bug**
I have integrated a Filament SwiftUI view through ObjC bridge. This view intends to be opened (initialized) and exited (deallocated) based on user input. It works fine without loading gltf assets. However when I add glb assets to the view (and deallocating assets when deallocating the view), things get a bit unstable. sometimes I get heap corruption exceptions like the following which will crash the app:

```
malloc: Heap corruption detected, free list is damaged at 0x280d504e0
*** Incorrect guard value: 4940120064
malloc: *** set a breakpoint in malloc_error_break to debug
```

**To Reproduce**
This issue occurs randomly but most likely a few open and exit of the Filament view with assets will trigger it. It happens on my repo now. I am looking for advice on initial triaging, whether this is something expected. If needed, I can create a test repo for you to repro.

**Expected behavior**
I expect the Filament view along with assets reloading without memory issues.

**Logs**
* From Xcode debug window:
```
MyApp(60334,0x16fa0b000) malloc: Heap corruption detected, free list is damaged at 0x282868d20
*** Incorrect guard value: 4990140416
MyApp(60334,0x16fa0b000) malloc: *** set a breakpoint in malloc_error_break to debug
```

* Memory graph debug with malloc allocation history
`malloc_history --quiet MyApp\[60334\]_2.memgraph --callTree 0x282868d20 --invert`
```
malloc_history Report Version:  2.0
Stack backtrace for allocation 0x282868d20

Call graph:
    1 (32 bytes) _malloc_zone_malloc  (in libsystem_malloc.dylib) + 0  [0x1c2bfa7f4]
      1 (32 bytes) operator new(unsigned long)  (in libc++abi.dylib) + 32  [0x2012778b0]
        1 (32 bytes) filament::FScene::FScene(filament::FEngine&)  (in MyApp) + 196  [0x100ff9948]
          1 (32 bytes) App::App(void*)  (in MyApp) + 36  [0x100a3d8d8]
            1 (32 bytes) -[FilamentRenderer initWithMetalKitView:]  (in MyApp) + 228  [0x100a1589c]
              1 (32 bytes) RenderView.Coordinator.init(mtkView:)  (in MyApp) + 188  [0x100a8727c]
                1 (32 bytes) RenderView.Coordinator.__allocating_init(mtkView:)  (in MyApp) + 40  [0x100a8713c]
                  1 (32 bytes) RenderView.makeCoordinator()  (in MyApp) + 72  [0x100a8701c]
                    1 (32 bytes) protocol witness for UIViewRepresentable.makeCoordinator() in conformance RenderView  (in MyApp) + 28  [0x100a87cf0]
                      1 (32 bytes) ???  (in SwiftUI)  load address 0x1b8359000 + 0xdffd04  [0x1b9158d04]
                        1 (32 bytes) ???  (in SwiftUI)  load address 0x1b8359000 + 0xdfee44  [0x1b9157e44]
                          1 (32 bytes) ???  (in SwiftUI)  load address 0x1b8359000 + 0x95524  [0x1b83ee524]
                            ...
```

* More from memory debugger from another run (not sure if they are helpful but listing here anyway)
Screen Shot 2022-11-04 at 2 25 42 PM

Screen Shot 2022-11-04 at 2 25 35 PM

* backtrace (**not showing the root cause in my view**) 
The malloc heap corruption exception sometimes happens within filament, sometimes happens outside of filament. I have listed two backtraces correspondingly.

```
thread #5, queue = 'com.apple.root.user-initiated-qos.cooperative', stop reason = breakpoint 1.1 3.1
    frame #0: 0x00000001c2c0e060 libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00000001c2c124cc libsystem_malloc.dylib`malloc_vreport + 428
    frame #2: 0x00000001c2c127e0 libsystem_malloc.dylib`malloc_zone_error + 100
    frame #3: 0x00000001c2c0c8b4 libsystem_malloc.dylib`nanov2_allocate_from_block + 548
    frame #4: 0x00000001c2c0b8e4 libsystem_malloc.dylib`nanov2_allocate + 124
    frame #5: 0x00000001c2c0b804 libsystem_malloc.dylib`nanov2_malloc + 64
    frame #6: 0x00000001c2bfa890 libsystem_malloc.dylib`_malloc_zone_malloc + 156
    frame #7: 0x00000002012778b0 libc++abi.dylib`operator new(unsigned long) + 32
    frame #8: 0x00000001005ff64c MyApp`filaflat::DictionaryReader::unflatten(filaflat::ChunkContainer const&, filamat::ChunkType, utils::FixedCapacityVector<utils::FixedCapacityVector<unsigned char, std::__1::allocator<unsigned char>, true>, std::__1::allocator<utils::FixedCapacityVector<unsigned char, std::__1::allocator<unsigned char>, true> >, true>&) + 432
    frame #9: 0x0000000100608778 MyApp`filament::MaterialParser::parse() + 228
    frame #10: 0x00000001006334ac MyApp`filament::Material::Builder::build(filament::Engine&) + 72
    frame #11: 0x000000010064aa18 MyApp`filament::gltfio::ArchiveCache::getMaterial(filament::gltfio::ArchiveRequirements const&) + 596
    frame #12: 0x000000010068454c MyApp`(anonymous namespace)::UbershaderProvider::getMaterial(filament::gltfio::MaterialKey*, std::__1::array<filament::gltfio::UvSet, 8ul>*, char const*) + 2320
    frame #13: 0x0000000100655538 MyApp`filament::gltfio::FAssetLoader::createPrimitive(cgltf_primitive const&, filament::gltfio::Primitive*, char const*) + 224
    frame #14: 0x00000001006539fc MyApp`filament::gltfio::FAssetLoader::createPrimitives(cgltf_data const*, cgltf_node const*, char const*) + 400
    frame #15: 0x0000000100653710 MyApp`filament::gltfio::FAssetLoader::recursePrimitives(cgltf_data const*, cgltf_node const*) + 104
    frame #16: 0x0000000100652ea4 MyApp`filament::gltfio::FAssetLoader::createRootAsset(cgltf_data const*) + 940
  * frame #17: 0x00000001006529d4 MyApp`filament::gltfio::FAssetLoader::createInstancedAsset(unsigned char const*, unsigned int, filament::gltfio::FilamentInstance**, unsigned long) + 204
  * ...
```

```
* thread #14, queue = 'com.apple.root.user-initiated-qos.cooperative', stop reason = breakpoint 1.1 3.1
  * frame #0: 0x00000001c2c0e060 libsystem_malloc.dylib`malloc_error_break
    frame #1: 0x00000001c2c124cc libsystem_malloc.dylib`malloc_vreport + 428
    frame #2: 0x00000001c2c127e0 libsystem_malloc.dylib`malloc_zone_error + 100
    frame #3: 0x00000001c2c0c8b4 libsystem_malloc.dylib`nanov2_allocate_from_block + 548
    frame #4: 0x00000001c2c0b8e4 libsystem_malloc.dylib`nanov2_allocate + 124
    frame #5: 0x00000001c2c0bf3c libsystem_malloc.dylib`nanov2_calloc + 160
    frame #6: 0x00000001c2bf9668 libsystem_malloc.dylib`_malloc_zone_calloc + 88
    frame #7: 0x00000001b4a8b478 CoreFoundation`_CFRuntimeCreateInstance + 436
    frame #8: 0x00000001b4a86df4 CoreFoundation`CFNumberCreate + 1036
    frame #9: 0x00000001aee83164 Foundation`-[NSPlaceholderNumber initWithDouble:] + 60
    frame #10: 0x00000001aee82cd8 Foundation`newJSONNumber + 1872
    frame #11: 0x00000001aeeeefa0 Foundation`newJSONValue + 1384
    frame #12: 0x00000001aeeeee4c Foundation`newJSONValue + 1044
    frame #13: 0x00000001aeeee1cc Foundation`newJSONObject + 568
    frame #14: 0x00000001aeeeec28 Foundation`newJSONValue + 496
    frame #15: 0x00000001aeeeee4c Foundation`newJSONValue + 1044
    frame #16: 0x00000001aeeee1cc Foundation`newJSONObject + 568
    frame #17: 0x00000001aeeeec28 Foundation`newJSONValue + 496
    frame #18: 0x00000001aeec5e04 Foundation`-[_NSJSONReader parseData:options:error:] + 1096
    frame #19: 0x00000001af2ffc40 Foundation`closure #1 () throws -> Any in Foundation.JSONDecoder.decode<τ_0_0 where τ_0_0: Swift.Decodable>(_: τ_0_0.Type, from: Foundation.Data) throws -> τ_0_0 + 112
```

**Desktop (please complete the following information):**
 - Xcode 14.1 on MacOS 12.6.1
 - Filament 1.28.2 installed through cocoapod. 

**Smartphone (please complete the following information):**
 - Device: iOS 16 iPhone 13

**Additional context**
The glb assets are downloaded to cache directory.

### PR DESCRIPTION
**Pull request by bejado**
This should fix #6275.

### CODE REVIEW

File: filament/src/BufferPoolAllocator.h [hunk 1]
```diff
@@ -92,7 +92,6 @@ class BufferPoolAllocator {
 
 template<size_t POOL_SIZE, size_t ALIGNMENT, typename AllocatorPolicy, typename LockingPolicy>
 BufferPoolAllocator<POOL_SIZE, ALIGNMENT, AllocatorPolicy, LockingPolicy>::~BufferPoolAllocator() noexcept {
-    assert_invariant(mOutstandingBuffers == mEntries.size());
```
Comment (bejado) [inline filament/src/BufferPoolAllocator.h:95]: @pixelflinger can you think of a way to make this assertion work? Otherwise, we can remove `mOustandingBuffers` since I don't think it's being used for anything.

Comment (pixelflinger) [reply filament/src/BufferPoolAllocator.h:95]: we could count the number of callbacks registered, the number of callbacks that "came back" and check that outstandingBuffer matches the difference?

Not sure if it is worth it.

File: filament/src/details/Scene.cpp [hunk 2]
```diff
@@ -281,16 +282,24 @@ void FScene::updateUBOs(
         buffer[i] = uboData[i];
     }
 
+    // We capture state shared between Scene and the update buffer callback, because the Scene could
+    // be destroyed before the callback executes.
+    std::weak_ptr<SharedState>* const weakShared = new std::weak_ptr<SharedState>(mSharedState);
```
Comment (pixelflinger) [inline filament/src/details/Scene.cpp:287]: I can't think of a way to avoid this allocation.

**Review by pixelflinger — APPROVED** [review]

File: filament/src/BufferPoolAllocator.h (hunk 1 above)
Comment (bejado) [reply filament/src/BufferPoolAllocator.h:95]: Yeah, I agree
