### PR TITLE
Fix a possible out of bound access on the GPU

### LINKED ISSUE #4388: a crash when viewing glTF with point/spot lights with filament-1.11.0 on iOS
screenshot

### PR DESCRIPTION
**Pull request by pixelflinger**
When calculating the froxel z slice, a depth buffer value of exactly
1 (i.e. far plane) would map to after the last slice, this value
must be clamped.

made the code more readable, hopefully.

Fixes #4388

### CODE REVIEW

File: shaders/src/light_punctual.fs [hunk 1]
```diff
@@ -30,9 +30,15 @@ uvec3 getFroxelCoords(const highp vec3 fragCoords) {
...
             vec2(frameUniforms.oneOverFroxelDimension, frameUniforms.oneOverFroxelDimensionY));
 
-    froxelCoord.z = uint(max(0.0,
-            log2(frameUniforms.zParams.x * fragCoords.z + frameUniforms.zParams.y) *
-                    frameUniforms.zParams.z + frameUniforms.zParams.w));
+    // go from screen-space (non-inverted) Z to normalized view-space Z (i.e. scaled by 1/zLightFar)
+    // (see Froxelizer.cpp)
+    highp float viewSpaceNormalizedZ = frameUniforms.zParams.x * fragCoords.z + frameUniforms.zParams.y;
+    // compute the sliceZ mapping
+    highp float sliceZ = log2(viewSpaceNormalizedZ) * frameUniforms.zParams.z + frameUniforms.zParams.w;
```
Comment (romainguy) [inline shaders/src/light_punctual.fs:37]: Does the slice need to be highp? That seems unnecessary

**Review by romainguy — APPROVED** [review]

**Review by bejado — APPROVED** [review]

File: shaders/src/light_punctual.fs (hunk 1 above)
Comment (pixelflinger) [reply shaders/src/light_punctual.fs:37]: yes good point
