### PR TITLE
gltfio: expose all resource URI strings.

### LINKED ISSUE #1593: Some animated glTFs fail to load the .bin file
**Describe the bug**
I tried to load the following animation glTF file with filament.
[AnimatedTriangle.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedTriangle)
[SimpleSkin.gltf](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_019_SimpleSkin.md)
However, an error was output to the console and the model was not displayed.

```
filament.js:formatted:1205 
Unable to load animation.bin
put_char	@	filament.js:formatted:1205
write	@	filament.js:formatted:1124
write	@	filament.js:formatted:3323
doWritev	@	filament.js:formatted:4344
___syscall146	@	filament.js:formatted:4425
(anonymous)	@	wasm-0066135e-1970:72
(anonymous)	@	wasm-0066135e-2000:49
(anonymous)	@	wasm-0066135e-2031:11
(anonymous)	@	wasm-0066135e-2030:9
(anonymous)	@	wasm-0066135e-1527:25
(anonymous)	@	wasm-0066135e-1652:539
(anonymous)	@	wasm-0066135e-501:34
(anonymous)	@	wasm-0066135e-735:10
Module.dynCall_iiii	@	filament.js:formatted:10150
dynCall_iiii_85	@	VM2137:4
gltfio$ResourceLoader$loadResources	@	VM2267:9
finalize	@	filament.js:formatted:10620
(anonymous)	@	index.js:95
```

**To Reproduce**

[filament + AnimatedTriangle.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=AnimatedTriangle&scale=1&type=glTF)
[filament + SimpleSkin.gltf result:](https://cx20.github.io/gltf-test/examples/filament/index.html?category=tutorialModels&model=SimpleSkin&scale=1&type=glTF)

**Expected behavior**
I expect the animated glTF model to load and display correctly.

**Screenshots**
There is no reference screen because nothing is displayed.

**Desktop (please complete the following information):**
- OS: Windows 10 Version 1903 (OS Build 18362.295)
- GPU: Intel HD Graphics 520
- Backend: ANGLE
- Browser: Chrome 76

### PR DESCRIPTION
**Pull request by prideout**
Some buffers (like animation data) do not contain any vertex data but web-based clients still need to know about them.

This interface is much simpler than the bindings lists, and in fact we might remove the binding lists in the future to simplify the API.

Fixes #1593.

### CODE REVIEW

File: libs/gltfio/include/gltfio/FilamentAsset.h [hunk 1]
```diff
@@ -77,6 +77,10 @@ class FilamentAsset {
     size_t getTextureBindingCount() const noexcept;
     const TextureBinding* getTextureBindings() const noexcept;
 
+    /** Gets resource URLs for all externally-referenced buffers. */
+    size_t getResourceUrlCount() const noexcept;
```
Comment (bejado) [inline libs/gltfio/include/gltfio/FilamentAsset.h]: Rename to `getResourceUriCount` and `getResourceUris` for consistency? I think this is what the official spec refers to them as. (Also update comment here and other locations in this PR)

Comment (prideout) [reply libs/gltfio/include/gltfio/FilamentAsset.h]: Good point, added a commit for this renaming.
