### PR TITLE
Retrieve morph target count from the primitive

### LINKED ISSUE #5289: Morphing does not work anymore
**Describe the bug**
I used version `1.17.0` and applied morphing with the `setMorphWeights(i, weights)` method. This version threw some "Fatal signal 11" errors after several calls to `loadModelGlb()` so I updated to the latest one `1.20.1`. Performance is better and I don't see errors but morphing stopped working. Filament ignores `setMorphWeights` calls.  

**To Reproduce**
1. Implement morphing with version `1.17.0`
2. Update to `1.20.1`
3. Change `setMorphWeights(i, weights)` to `setMorphWeights(i, weights, 0)` to have successful compilation 
4. Morphing does not work anymore

**Expected behavior**
Morphing should work like before. 

**Desktop (please complete the following information):**
 - OS: Android
 - Backend: OpenGL

**Smartphone (please complete the following information):**
 - Device: OnePlus 6
 - OS: Android 11

**Additional context**
I see that there's a new API – `MorphTargetBuffer` but I don't see any example regarding how to use it. All I need is a simple call that lets me morph a blend shape with a given value. `setMorphWeights(i, weights)` worked fine. 

Also, I see that it's possible to enable legacy morphing using `MaterialBuilder` but it's a part of the Filamat and I don't have this dependency.

### PR DESCRIPTION
**Pull request by daemyung**
Morph weights can be zero even if the primitive has morph targets.

Fixes #5289

### CODE REVIEW

File: libs/gltfio/src/AssetLoader.cpp [hunk 1]
```diff
@@ -444,22 +444,20 @@ void FAssetLoader::createRenderable(const cgltf_data* srcAsset, const cgltf_node
...
         if (!getPrimitiveType(inputPrim->type, &primType)) {
             slog.e << "Unsupported primitive type in " << name << io::endl;
         }
 
-        if (numMorphTargets > 0 && inputPrim->targets_count != numMorphTargets) {
-            slog.e << "Sister primitives must all have the same number of morph targets."
-                   << io::endl;
-            mError = true;
-            continue;
+        if (inputPrim->targets_count > 0) {
```
Comment (bejado) [inline libs/gltfio/src/AssetLoader.cpp:455]: I don't think this will catch cases where some primitives have no morph targets, but others do. Is that allowed? For example:
```
Primitive 0: 0 morph targets
Primitive 1: 5 morph targets
Primitive 2: 5 morph targets
```

File: libs/gltfio/src/AssetLoader.cpp [hunk 2]
```diff
@@ -444,22 +444,20 @@ void FAssetLoader::createRenderable(const cgltf_data* srcAsset, const cgltf_node
...
+            if (numMorphTargets > 0 && inputPrim->targets_count != numMorphTargets) {
+                slog.e << "Sister primitives must all have the same number of morph targets."
+                       << io::endl;
+            }
```
Comment (bejado) [inline libs/gltfio/src/AssetLoader.cpp:459]: Should we still set `mError = true` here?

File: libs/gltfio/src/AssetLoader.cpp (hunk 1 above)
Comment (daemyung) [reply libs/gltfio/src/AssetLoader.cpp:455]: This case is invalid glTF spec so it must be not allowed.

File: libs/gltfio/src/AssetLoader.cpp (hunk 2 above)
Comment (daemyung) [reply libs/gltfio/src/AssetLoader.cpp:459]: Actually I just revert changes. Your suggestion will be great. I will update this.

File: libs/gltfio/src/AssetLoader.cpp [hunk 3]
```diff
@@ -535,8 +536,8 @@ void FAssetLoader::createRenderable(const cgltf_data* srcAsset, const cgltf_node
     // node weights are provided, they override the ones specified on the mesh.
     if (numMorphTargets > 0) {
         RenderableManager::Instance renderable = mRenderableManager.getInstance(entity);
-        const auto size = std::min(MAX_MORPH_TARGETS, std::max(mesh->weights_count, node->weights_count));
-        std::vector<float> weights(size);
+        const auto size = std::min(MAX_MORPH_TARGETS, numMorphTargets);
+        std::vector<float> weights(size, 0.0f);
```
Comment (prideout) [inline libs/gltfio/src/AssetLoader.cpp:540]: I realize this is pre-existing, but as a cleanup can we change this to FixedCapacityVector?  std::vector isn't used anywhere else in this file.  In fact I would also like SkinVector to also be FixedCapacityVector.

**Review by prideout — APPROVED** [review]
Looks fine, however I do have one a cleanup idea (std::vector => FixedCapacityVector).

File: libs/gltfio/src/AssetLoader.cpp (hunk 1 above)
Comment (bejado) [reply libs/gltfio/src/AssetLoader.cpp:455]: My point is that the scenario where the first primitive has no morph targets (but other primitives do) will _not_ be reported as "Sister primitives must all have the same number of morph targets." It's an invalid glTF file, yes, but so are the ones where we show that message. We should be consistent.

```
            "primitives" : [
                {
                    "attributes" : {
                        "POSITION" : 0,
                        "NORMAL" : 1,
                        "TEXCOORD_0" : 2
                    },
                    "indices" : 3,
                    "material" : 0
                    "targets" : [
                    ]
                },
                {
                    "attributes" : {
                        "POSITION" : 8,
                        "NORMAL" : 9,
                        "TEXCOORD_0" : 10
                    },
                    "indices" : 3,
                    "material" : 1,
                    "targets" : [
                        {
                            "POSITION" : 11,
                            "NORMAL" : 12
                        },
                        {
                            "POSITION" : 13,
                            "NORMAL" : 14
                        }
                    ]
                },
                // etc..
            ],

```

**Review by bejado — CHANGES_REQUESTED** [review]

File: libs/gltfio/src/AssetLoader.cpp (hunk 1 above)
Comment (daemyung) [reply libs/gltfio/src/AssetLoader.cpp:455]: I get your point. I have updated code. First get the morph target count from the first primitive if the first primitive is exist. Second check other primitives have same number of morph target count.

File: libs/gltfio/src/AssetLoader.cpp (hunk 3 above)
Comment (daemyung) [reply libs/gltfio/src/AssetLoader.cpp:540]: It's updated.

**Review by pixelflinger — APPROVED** [review]

**Review by bejado — APPROVED** [review]
