### PR TITLE
Work around Qualcomm issue with point lights.

### LINKED ISSUE #3602: Android: Point lights don't work with Vulkan + Qualcomm
Point lights don't seem to work in `sample-gltf-viewer` when using the Vulkan backend.

**To Reproduce**

I'm using the QR code branch to make it easy to upload a .glb test file: https://github.com/google/filament/pull/3599

1. Build Filament for Android:

```
./build.sh -c -i -p android release
```

2. Patch `sample-gltf-viewer` to enable the Vulkan backend and turn down IBL intensity:

```
--- a/android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
+++ b/android/samples/sample-gltf-viewer/src/main/java/com/google/android/filament/gltf/MainActivity.kt
@@ -30,6 +30,7 @@ import androidx.camera.core.Preview
 import androidx.camera.lifecycle.ProcessCameraProvider
 import androidx.core.content.ContextCompat
 import androidx.lifecycle.LifecycleOwner
+import com.google.android.filament.Engine
 import com.google.android.filament.utils.KtxLoader
 import com.google.android.filament.utils.ModelViewer
 import com.google.android.filament.utils.Utils
@@ -89,7 +90,7 @@ class MainActivity : AppCompatActivity() {

         doubleTapDetector = GestureDetector(applicationContext, doubleTapListener)

-        modelViewer = ModelViewer(surfaceView)
+        modelViewer = ModelViewer(surfaceView, Engine.create(Engine.Backend.VULKAN))

         surfaceView.setOnTouchListener { _, event ->
             modelViewer.onTouchEvent(event)
@@ -256,7 +257,7 @@ class MainActivity : AppCompatActivity() {
         val ibl = "default_env"
         readCompressedAsset("envs/$ibl/${ibl}_ibl.ktx").let {
             scene.indirectLight = KtxLoader.createIndirectLight(engine, it)
-            scene.indirectLight!!.intensity = 30_000.0f
+            scene.indirectLight!!.intensity = 3000.0f
         }
         readCompressedAsset("envs/$ibl/${ibl}_skybox.ktx").let {
             scene.skybox = KtxLoader.createSkybox(engine, it)
```

3. Install on device

```
./gradlew samples:sample-gltf-viewer:InstallDebug
```

4. Run and upload [this glb test file](https://github.com/google/filament/files/6071072/rgb-lights.glb.zip), which contains 3 point lights.

5. Notice the difference between Vulkan / OpenGL:

Vulkan:

Screenshot_20210301-164027

OpenGL:

Screenshot_20210301-164122

It's peculiar on Vulkan, there are black smears where the point lights should be:

Screenshot_20210301-164027

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android 11 userdebug RQ1A.210205.004

### PR DESCRIPTION
**Pull request by prideout**
Fixes #3602.

### CODE REVIEW

**Comment by prideout** [comment]
This is not a precision bug, but specifying highp here is the easiest way to trick the optimizer into generating SPIRV code that doesn't break Qualcomm.  I tried lots of other hacks to no avail.

**Review by romainguy — APPROVED** [review]
@pixelflinger

It seems fine but I want to make sure we don't end up doing extra work in fp32 because of this. Everything related to exposure was carefully designed to be in fp16 as much as possible.

**Comment by pixelflinger** [comment]
Woah, this is wild.

So it's this a highp problem in the end? I don't even understand why this specific uniform has an effect.

Did this end up changing a lot of things in the final optimized shader?

**Comment by prideout** [comment]
> Woah, this is wild.
> 
> So it's this a highp problem in the end? I don't even understand why this specific uniform has an effect.
> 
> Did this end up changing a lot of things in the final optimized shader?

This uniform is used to compute an intensity that seems to get zeroed out by the qcom driver.  By using highp here, we are forcing the optimizer to avoid simplification of an expression that seems to trigger the bug.

So... it's actually not highp related at all, but I wasn't able to trick the optimizer in any other way.

File: shaders/src/light_punctual.fs [hunk 1]
```diff
@@ -128,7 +128,7 @@ Light getLight(const uint index) {
     // and populate the Light structure
     Light light;
     light.colorIntensity.rgb = colorIntensity.rgb;
-    light.colorIntensity.w = computePreExposedIntensity(colorIntensity.w, frameUniforms.exposure);
+    light.colorIntensity.w = computePreExposedIntensity(colorIntensity.w, getExposure());
```
Comment (romainguy) [inline shaders/src/light_punctual.fs:131]: Sooo… here it would make more sense to keep accessing the uniform since this particular function will make the value highp again to do a highp multiplication.

File: shaders/src/shading_lit.fs [hunk 2]
```diff
@@ -296,7 +296,7 @@ vec4 evaluateLights(const MaterialInputs material) {
 void addEmissive(const MaterialInputs material, inout vec4 color) {
 #if defined(MATERIAL_HAS_EMISSIVE)
     highp vec4 emissive = material.emissive;
-    highp float attenuation = mix(1.0, frameUniforms.exposure, emissive.w);
+    highp float attenuation = mix(1.0, getExposure(), emissive.w);
```
Comment (pixelflinger) [inline shaders/src/shading_lit.fs:299]: I don't think attenuation needs to be `highp` here, actually -- probably for another PR though.

File: shaders/src/shading_unlit.fs [hunk 3]
```diff
@@ -1,7 +1,7 @@
 void addEmissive(const MaterialInputs material, inout vec4 color) {
 #if defined(MATERIAL_HAS_EMISSIVE)
     highp vec4 emissive = material.emissive;
-    highp float attenuation = mix(1.0, frameUniforms.exposure, emissive.w);
+    highp float attenuation = mix(1.0, getExposure(), emissive.w);
```
Comment (pixelflinger) [inline shaders/src/shading_unlit.fs:4]: I don't think attenuation needs to be `highp` here, actually -- probably for another PR though.

Comment (romainguy) [reply shaders/src/shading_unlit.fs:4]: It has to be, it's effectively an exposure value and exposure needs to be highp. It's pre-exposed intensities (lightIntensity * exposure) that do not need to be highp.
