### PR TITLE
WASM: Set CONFIG_MAX_INSTANCES to a small value.

### LINKED ISSUE #5859: Lighting singularity in web viewer
**Describe the bug**
Web viewer shows a strange lighting singularity.

**To Reproduce**
1. https://google.github.io/filament/viewer/
2. Drag-and-drop the Duck sample model (https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/1.0/Duck)

**Expected behavior**
The lighting should be smooth and continuous across the surface. However it is showing a singularity.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - GPU: NVIDIA RTX 2070 laptop
 - Browser: Chrome Version 103.0.5060.134 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by prideout**
This is a workaround for the following Chrome issues:

https://crbug.com/1348017 Compiling GLSL is very slow with struct arrays
https://crbug.com/1348363 Lighting looks wrong with D3D11 but not OpenGL

This requires a rebuild of materials for WebGL users.

Fixes #5859.

### CODE REVIEW

**Review by bejado — APPROVED** [review]

**Review by pixelflinger — APPROVED** [review]

File: libs/filabridge/include/filament/MaterialEnums.h [hunk 1]
```diff
@@ -27,7 +27,7 @@
 namespace filament {
 
 // update this when a new version of filament wouldn't work with older materials
-static constexpr size_t MATERIAL_VERSION = 26;
+static constexpr size_t MATERIAL_VERSION = 27;
```
Comment (pixelflinger) [inline libs/filabridge/include/filament/MaterialEnums.h:30]: @bejado do we need to up the material version for each breaking change, or only when we branch the rc?

Comment (bejado) [reply libs/filabridge/include/filament/MaterialEnums.h:30]: Typically we update the material version when the breaking change is made, which is how I know to bump the middle version. Either way is fine though
