### PR TITLE
Fix fence-related Vulkan validation warnings.

### LINKED ISSUE #1051: Vulkan validation error: "VkFence is simultaneously used in thread A and thread B"
According to the spec, VkFence is an externally synchronized object and therefore cannot be accessed by more than one thread. Initially this struck me as odd, but Mike Stroyen (ex-google, now retired) provides a reasonable explanation here:

https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/519

To get around this maybe our Vulkan backend should spin up a new thread just for vkQueueSubmit and vkWaitForFences.  However queues *also* need to be externally synchronized so we might run into a domino effect of moving things into this tertiary thread.

Another possibility is to simply poll all fences of interest from the same thread that we already submit the queue on, aka the driver thread.  However polling at `beginThread` is too infrequent and would give bad timing results to the FrameInfoManager.  (It would be nice to be able to override the behavior in `CommandBufferQueue::waitForCommands`...)

Vulkan provides timing queries, so maybe we should expose those instead of fences.  However the OpenGL ES core spec does not support these, so it seems weird to expose it at the DriverAPI level.

### PR DESCRIPTION
**Pull request by prideout**
This adds a condition variable to ensure that the wait occurs after the
flush.

Longer term we would like to not use fences to measure frame time and
instead use timing queries.

Fixes #1051.

### CODE REVIEW

File: filament/backend/src/vulkan/VulkanContext.cpp [hunk 1]
```diff
@@ -546,7 +548,7 @@ void flushWorkCommandBuffer(VulkanContext& context) {
     };
     vkEndCommandBuffer(work.cmdbuffer);
     vkQueueSubmit(context.graphicsQueue, 1, &submitInfo, work.fence->fence);
-    work.submitted = true;
+    work.fence->submitted = true;
```
Comment (bejado) [inline filament/backend/src/vulkan/VulkanContext.cpp]: Do you need to lock / unlock the mutex here?

Comment (prideout) [reply filament/backend/src/vulkan/VulkanContext.cpp]: This is the "work" command buffer which the DriverAPI client should never wait on.

Comment (bejado) [reply filament/backend/src/vulkan/VulkanContext.cpp]: Got it!
